debug = false
listenAddr = "0.0.0.0:2021"
advertiseAddr = "127.0.0.1:2021"

[bolt]
    db = "cassemdb.kv"

[raft]
    bind = "http://cassemdb1:3021"
    cluster = "http://cassemdb1:3021,http://cassemdb2:3022,http://cassemdb3:3023"
    snapCount = 300
