debug = false
addr    = ":2023"
[bolt]
        dir       = "./debugdata/d3"
        db        = "cassemdb.kv"
[raft]
    base = "./debugdata/d3"
    bind = "127.0.0.1:3023"
    clusterAddresses = [
        "127.0.0.1:3021",
        "127.0.0.1:3022",
        "127.0.0.1:3023"
    ]
    bootstrapCluster = false
