debug = false
[persistence]
    [persistence.bbolt]
            dir       = "./debugdata/d2"
            db        = "cassem.db"

[server]
    [server.http]
        addr    = ":2022"
    [server.raft]
        base = "./debugdata/d2"
        bind = "127.0.0.1:3022"
        serverId = "d2"
        join = ["127.0.0.1:2021"]
