debug = false
addr    = ":2023"
[bolt]
        dir       = "./debugdata/d3"
        db        = "cassemdb.kv"
[raft]
    nodeId = 3
    base = "./debugdata/d3"
    bind = "127.0.0.1:3023"
    peers = [
        "http://127.0.0.1:3021",
        "http://127.0.0.1:3022",
        "http://127.0.0.1:3023"
    ]
    bootstrapCluster = false
