debug = false
addr = ":2021"
[bolt]
    db = "cassemdb.kv"
[raft]
    bind = "127.0.0.1:3021"
    peers = [
        "http://127.0.0.1:3021",
        "http://127.0.0.1:3022",
        "http://127.0.0.1:3023"
    ]
    bootstrapCluster = false
    snapCount = 300
