debug = false
addr    = ":2022"
[bolt]
        dir       = "./debugdata/d2"
        db        = "cassemdb.kv"
[raft]
    nodeId = 2
    base = "./debugdata/d2"
    bind = "127.0.0.1:3022"
    peers = [
        "http://127.0.0.1:3021",
        "http://127.0.0.1:3022",
        "http://127.0.0.1:3023"
    ]
    bootstrapCluster = false
