prepare:
	@ mkdir d1 d2 d3

clear:
	@ rm -fr ./d1
	@ rm -fr ./d2
	@ rm -fr ./d3

run:
	echo "Step1: `go build build -o cassemdb path/to/cmd/cassemdb` here"
	echo "Step2: `./cassemdb --conf=./cassemdb1.toml` and so on"