syntax = "proto3";

import "concept/types.proto";
import "buf/validate/validate.proto";

package cassem.agent;
option go_package = "github.com/yeqown/cassem/api/agent;agent";

message getElementReq {
  string          app = 1 [(buf.validate.field).string = {min_len: 3, max_len: 30, pattern: "^[A-Za-z0-9][A-Za-z0-9_-]*$"}];
  string          env = 2 [(buf.validate.field).string = {min_len: 3, max_len: 30, pattern: "^[A-Za-z0-9][A-Za-z0-9_-]*$"}];
  repeated string keys = 3 [(buf.validate.field).repeated = {unique: true, min_items: 1, max_items: 100, items: {string: {pattern: "^[A-Za-z0-9][A-Za-z0-9_-]*$"}}}];
}

message getElementResp {
  repeated cassem.concept.Element elems = 1;
}

message unregisterReq {
  string clientId = 1 [(buf.validate.field).string = {min_len: 5, max_len: 64}];
  string clientIp = 2 [(buf.validate.field).string.ip = true];
}

message registerReq {
  string clientId = 1 [(buf.validate.field).string = {min_len: 5, max_len: 64}];
  string clientIp = 2 [(buf.validate.field).string.ip = true];
  repeated concept.Instance.Watching watching = 3 [(buf.validate.field).ignore = IGNORE_IF_ZERO_VALUE];
}

message emptyResp {}

message watchReq {
  repeated concept.Instance.Watching watching = 1 [(buf.validate.field).ignore = IGNORE_IF_ZERO_VALUE];
  string clientId = 4 [(buf.validate.field).string = {min_len: 5, max_len: 64}];
  string clientIp = 5 [(buf.validate.field).string.ip = true];
}
message watchResp {
  cassem.concept.Element elem = 1;
}

// agent service provide API for client.
service agent {
  rpc GetElement(getElementReq) returns (getElementResp){};
  rpc Unregister(unregisterReq) returns (emptyResp){};
  rpc Register(registerReq) returns (emptyResp) {};
  rpc Renew(registerReq) returns (emptyResp) {};
  rpc Watch(watchReq) returns (stream watchResp) {};
}

message dispatchReq {
  repeated cassem.concept.Element elems = 1;
  repeated string instanceIds = 2;
}

message dispatchResp {}

// delivery service provide API for cassem.adm.
service delivery {
  rpc Dispatch(dispatchReq) returns (dispatchResp) {};
}