// Code generated by "stringer -type=action"; DO NOT EDIT.

package domain

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[actionSetKV-1]
	_ = x[actionChange-2]
}

const _action_name = "actionSetKVactionChange"

var _action_index = [...]uint8{0, 11, 23}

func (i action) String() string {
	i -= 1
	if i >= action(len(_action_index)-1) {
		return "action(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _action_name[_action_index[i]:_action_index[i+1]]
}
