// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: acl.proto

package concept

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User_Status int32

const (
	User_NORMAL User_Status = 0
	// FORBIDDEN indicates the user is forbidden to access the system.
	User_FORBIDDEN User_Status = 1
)

// Enum value maps for User_Status.
var (
	User_Status_name = map[int32]string{
		0: "NORMAL",
		1: "FORBIDDEN",
	}
	User_Status_value = map[string]int32{
		"NORMAL":    0,
		"FORBIDDEN": 1,
	}
)

func (x User_Status) Enum() *User_Status {
	p := new(User_Status)
	*p = x
	return p
}

func (x User_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (User_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_acl_proto_enumTypes[0].Descriptor()
}

func (User_Status) Type() protoreflect.EnumType {
	return &file_acl_proto_enumTypes[0]
}

func (x User_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use User_Status.Descriptor instead.
func (User_Status) EnumDescriptor() ([]byte, []int) {
	return file_acl_proto_rawDescGZIP(), []int{0, 0}
}

type User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// account
	Account        string      `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Nickname       string      `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	HashedPassword string      `protobuf:"bytes,3,opt,name=hashedPassword,proto3" json:"hashedPassword,omitempty"`
	Salt           string      `protobuf:"bytes,4,opt,name=salt,proto3" json:"salt,omitempty"`
	Status         User_Status `protobuf:"varint,5,opt,name=status,proto3,enum=cassem.concept.User_Status" json:"status,omitempty"`
}

func (x *User) Reset() {
	*x = User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_acl_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_acl_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_acl_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *User) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *User) GetHashedPassword() string {
	if x != nil {
		return x.HashedPassword
	}
	return ""
}

func (x *User) GetSalt() string {
	if x != nil {
		return x.Salt
	}
	return ""
}

func (x *User) GetStatus() User_Status {
	if x != nil {
		return x.Status
	}
	return User_NORMAL
}

// Casbin represent the casbin model.
type Casbin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Policies []*Casbin_Policy `protobuf:"bytes,1,rep,name=policies,proto3" json:"policies,omitempty"`
}

func (x *Casbin) Reset() {
	*x = Casbin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_acl_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Casbin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Casbin) ProtoMessage() {}

func (x *Casbin) ProtoReflect() protoreflect.Message {
	mi := &file_acl_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Casbin.ProtoReflect.Descriptor instead.
func (*Casbin) Descriptor() ([]byte, []int) {
	return file_acl_proto_rawDescGZIP(), []int{1}
}

func (x *Casbin) GetPolicies() []*Casbin_Policy {
	if x != nil {
		return x.Policies
	}
	return nil
}

type Casbin_Policy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ptype string `protobuf:"bytes,1,opt,name=Ptype,proto3" json:"Ptype,omitempty"`
	V0    string `protobuf:"bytes,2,opt,name=V0,proto3" json:"V0,omitempty"`
	V1    string `protobuf:"bytes,3,opt,name=V1,proto3" json:"V1,omitempty"`
	V2    string `protobuf:"bytes,4,opt,name=V2,proto3" json:"V2,omitempty"`
	V3    string `protobuf:"bytes,5,opt,name=V3,proto3" json:"V3,omitempty"`
	V4    string `protobuf:"bytes,6,opt,name=V4,proto3" json:"V4,omitempty"`
	V5    string `protobuf:"bytes,7,opt,name=V5,proto3" json:"V5,omitempty"`
}

func (x *Casbin_Policy) Reset() {
	*x = Casbin_Policy{}
	if protoimpl.UnsafeEnabled {
		mi := &file_acl_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Casbin_Policy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Casbin_Policy) ProtoMessage() {}

func (x *Casbin_Policy) ProtoReflect() protoreflect.Message {
	mi := &file_acl_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Casbin_Policy.ProtoReflect.Descriptor instead.
func (*Casbin_Policy) Descriptor() ([]byte, []int) {
	return file_acl_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Casbin_Policy) GetPtype() string {
	if x != nil {
		return x.Ptype
	}
	return ""
}

func (x *Casbin_Policy) GetV0() string {
	if x != nil {
		return x.V0
	}
	return ""
}

func (x *Casbin_Policy) GetV1() string {
	if x != nil {
		return x.V1
	}
	return ""
}

func (x *Casbin_Policy) GetV2() string {
	if x != nil {
		return x.V2
	}
	return ""
}

func (x *Casbin_Policy) GetV3() string {
	if x != nil {
		return x.V3
	}
	return ""
}

func (x *Casbin_Policy) GetV4() string {
	if x != nil {
		return x.V4
	}
	return ""
}

func (x *Casbin_Policy) GetV5() string {
	if x != nil {
		return x.V5
	}
	return ""
}

var File_acl_proto protoreflect.FileDescriptor

var file_acl_proto_rawDesc = []byte{
	0x0a, 0x09, 0x61, 0x63, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x63, 0x61, 0x73,
	0x73, 0x65, 0x6d, 0x2e, 0x63, 0x6f, 0x6e, 0x63, 0x65, 0x70, 0x74, 0x1a, 0x22, 0x65, 0x6e, 0x76,
	0x6f, 0x79, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2d, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65,
	0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x85, 0x02, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x12, 0x21, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x72, 0x02,
	0x60, 0x01, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x25, 0x0a, 0x08, 0x6e,
	0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x09, 0xfa,
	0x42, 0x06, 0x72, 0x04, 0x10, 0x01, 0x18, 0x40, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x31, 0x0a, 0x0e, 0x68, 0x61, 0x73, 0x68, 0x65, 0x64, 0x50, 0x61, 0x73, 0x73,
	0x77, 0x6f, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x42, 0x09, 0xfa, 0x42, 0x06, 0x72,
	0x04, 0x10, 0x06, 0x18, 0x0c, 0x52, 0x0e, 0x68, 0x61, 0x73, 0x68, 0x65, 0x64, 0x50, 0x61, 0x73,
	0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x1c, 0x0a, 0x04, 0x73, 0x61, 0x6c, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x42, 0x08, 0xfa, 0x42, 0x05, 0x72, 0x03, 0x98, 0x01, 0x08, 0x52, 0x04, 0x73,
	0x61, 0x6c, 0x74, 0x12, 0x3d, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x63, 0x61, 0x73, 0x73, 0x65, 0x6d, 0x2e, 0x63, 0x6f, 0x6e,
	0x63, 0x65, 0x70, 0x74, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x42, 0x08, 0xfa, 0x42, 0x05, 0x82, 0x01, 0x02, 0x10, 0x01, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x22, 0x23, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0a, 0x0a, 0x06,
	0x4e, 0x4f, 0x52, 0x4d, 0x41, 0x4c, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x46, 0x4f, 0x52, 0x42,
	0x49, 0x44, 0x44, 0x45, 0x4e, 0x10, 0x01, 0x22, 0xc3, 0x01, 0x0a, 0x06, 0x43, 0x61, 0x73, 0x62,
	0x69, 0x6e, 0x12, 0x39, 0x0a, 0x08, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x63, 0x61, 0x73, 0x73, 0x65, 0x6d, 0x2e, 0x63, 0x6f,
	0x6e, 0x63, 0x65, 0x70, 0x74, 0x2e, 0x43, 0x61, 0x73, 0x62, 0x69, 0x6e, 0x2e, 0x50, 0x6f, 0x6c,
	0x69, 0x63, 0x79, 0x52, 0x08, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x65, 0x73, 0x1a, 0x7e, 0x0a,
	0x06, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x50, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x50, 0x74, 0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a,
	0x02, 0x56, 0x30, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x56, 0x30, 0x12, 0x0e, 0x0a,
	0x02, 0x56, 0x31, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x56, 0x31, 0x12, 0x0e, 0x0a,
	0x02, 0x56, 0x32, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x56, 0x32, 0x12, 0x0e, 0x0a,
	0x02, 0x56, 0x33, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x56, 0x33, 0x12, 0x0e, 0x0a,
	0x02, 0x56, 0x34, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x56, 0x34, 0x12, 0x0e, 0x0a,
	0x02, 0x56, 0x35, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x56, 0x35, 0x42, 0x2e, 0x5a,
	0x2c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x79, 0x65, 0x71, 0x6f,
	0x77, 0x6e, 0x2f, 0x63, 0x61, 0x73, 0x73, 0x65, 0x6d, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f,
	0x6e, 0x63, 0x65, 0x70, 0x74, 0x3b, 0x63, 0x6f, 0x6e, 0x63, 0x65, 0x70, 0x74, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_acl_proto_rawDescOnce sync.Once
	file_acl_proto_rawDescData = file_acl_proto_rawDesc
)

func file_acl_proto_rawDescGZIP() []byte {
	file_acl_proto_rawDescOnce.Do(func() {
		file_acl_proto_rawDescData = protoimpl.X.CompressGZIP(file_acl_proto_rawDescData)
	})
	return file_acl_proto_rawDescData
}

var file_acl_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_acl_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_acl_proto_goTypes = []interface{}{
	(User_Status)(0),      // 0: cassem.concept.User.Status
	(*User)(nil),          // 1: cassem.concept.User
	(*Casbin)(nil),        // 2: cassem.concept.Casbin
	(*Casbin_Policy)(nil), // 3: cassem.concept.Casbin.Policy
}
var file_acl_proto_depIdxs = []int32{
	0, // 0: cassem.concept.User.status:type_name -> cassem.concept.User.Status
	3, // 1: cassem.concept.Casbin.policies:type_name -> cassem.concept.Casbin.Policy
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_acl_proto_init() }
func file_acl_proto_init() {
	if File_acl_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_acl_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_acl_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Casbin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_acl_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Casbin_Policy); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_acl_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_acl_proto_goTypes,
		DependencyIndexes: file_acl_proto_depIdxs,
		EnumInfos:         file_acl_proto_enumTypes,
		MessageInfos:      file_acl_proto_msgTypes,
	}.Build()
	File_acl_proto = out.File
	file_acl_proto_rawDesc = nil
	file_acl_proto_goTypes = nil
	file_acl_proto_depIdxs = nil
}
