// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: types.proto

package concept

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ContentType enumerates all built-in content types those Element's
// raw could be.
type ContentType int32

const (
	ContentType_UNKNOWN ContentType = 0
	// application/json
	ContentType_JSON ContentType = 1
	// application/toml
	ContentType_TOML ContentType = 2
	// application/ini
	ContentType_INI ContentType = 3
	// application/plaintext
	ContentType_PLAINTEXT ContentType = 4
)

// Enum value maps for ContentType.
var (
	ContentType_name = map[int32]string{
		0: "UNKNOWN",
		1: "JSON",
		2: "TOML",
		3: "INI",
		4: "PLAINTEXT",
	}
	ContentType_value = map[string]int32{
		"UNKNOWN":   0,
		"JSON":      1,
		"TOML":      2,
		"INI":       3,
		"PLAINTEXT": 4,
	}
)

func (x ContentType) Enum() *ContentType {
	p := new(ContentType)
	*p = x
	return p
}

func (x ContentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContentType) Descriptor() protoreflect.EnumDescriptor {
	return file_types_proto_enumTypes[0].Descriptor()
}

func (ContentType) Type() protoreflect.EnumType {
	return &file_types_proto_enumTypes[0]
}

func (x ContentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContentType.Descriptor instead.
func (ContentType) EnumDescriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{0}
}

type ChangeOp int32

const (
	ChangeOp_UNDEFINED ChangeOp = 0
	ChangeOp_NEW       ChangeOp = 1
	ChangeOp_UPDATE    ChangeOp = 2
	ChangeOp_DELETE    ChangeOp = 3
)

// Enum value maps for ChangeOp.
var (
	ChangeOp_name = map[int32]string{
		0: "UNDEFINED",
		1: "NEW",
		2: "UPDATE",
		3: "DELETE",
	}
	ChangeOp_value = map[string]int32{
		"UNDEFINED": 0,
		"NEW":       1,
		"UPDATE":    2,
		"DELETE":    3,
	}
)

func (x ChangeOp) Enum() *ChangeOp {
	p := new(ChangeOp)
	*p = x
	return p
}

func (x ChangeOp) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChangeOp) Descriptor() protoreflect.EnumDescriptor {
	return file_types_proto_enumTypes[1].Descriptor()
}

func (ChangeOp) Type() protoreflect.EnumType {
	return &file_types_proto_enumTypes[1]
}

func (x ChangeOp) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChangeOp.Descriptor instead.
func (ChangeOp) EnumDescriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{1}
}

type AppMetadata_Status int32

const (
	AppMetadata_INUSE AppMetadata_Status = 0
	// DEPRECATED represents the app is deprecated. It can only read but update.
	AppMetadata_DEPRECATED AppMetadata_Status = 1
)

// Enum value maps for AppMetadata_Status.
var (
	AppMetadata_Status_name = map[int32]string{
		0: "INUSE",
		1: "DEPRECATED",
	}
	AppMetadata_Status_value = map[string]int32{
		"INUSE":      0,
		"DEPRECATED": 1,
	}
)

func (x AppMetadata_Status) Enum() *AppMetadata_Status {
	p := new(AppMetadata_Status)
	*p = x
	return p
}

func (x AppMetadata_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AppMetadata_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_types_proto_enumTypes[2].Descriptor()
}

func (AppMetadata_Status) Type() protoreflect.EnumType {
	return &file_types_proto_enumTypes[2]
}

func (x AppMetadata_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AppMetadata_Status.Descriptor instead.
func (AppMetadata_Status) EnumDescriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{2, 0}
}

type ElementOperation_Op int32

const (
	ElementOperation_INVALID ElementOperation_Op = 0
	ElementOperation_SET     ElementOperation_Op = 1
	ElementOperation_UNSET   ElementOperation_Op = 2
	ElementOperation_PUBLISH ElementOperation_Op = 3
)

// Enum value maps for ElementOperation_Op.
var (
	ElementOperation_Op_name = map[int32]string{
		0: "INVALID",
		1: "SET",
		2: "UNSET",
		3: "PUBLISH",
	}
	ElementOperation_Op_value = map[string]int32{
		"INVALID": 0,
		"SET":     1,
		"UNSET":   2,
		"PUBLISH": 3,
	}
)

func (x ElementOperation_Op) Enum() *ElementOperation_Op {
	p := new(ElementOperation_Op)
	*p = x
	return p
}

func (x ElementOperation_Op) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ElementOperation_Op) Descriptor() protoreflect.EnumDescriptor {
	return file_types_proto_enumTypes[3].Descriptor()
}

func (ElementOperation_Op) Type() protoreflect.EnumType {
	return &file_types_proto_enumTypes[3]
}

func (x ElementOperation_Op) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ElementOperation_Op.Descriptor instead.
func (ElementOperation_Op) EnumDescriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{3, 0}
}

// Element represent a config element with specific version.
type Element struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// refer ElementMetadata
	Metadata *ElementMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// raw data in the version.
	Raw []byte `protobuf:"bytes,2,opt,name=raw,proto3" json:"raw,omitempty"`
	// version number start since 1.
	Version int32 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	// indicates published or not.
	Published bool `protobuf:"varint,4,opt,name=published,proto3" json:"published,omitempty"`
}

func (x *Element) Reset() {
	*x = Element{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Element) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Element) ProtoMessage() {}

func (x *Element) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Element.ProtoReflect.Descriptor instead.
func (*Element) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{0}
}

func (x *Element) GetMetadata() *ElementMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Element) GetRaw() []byte {
	if x != nil {
		return x.Raw
	}
	return nil
}

func (x *Element) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Element) GetPublished() bool {
	if x != nil {
		return x.Published
	}
	return false
}

// ElementMetadata contains metadata of one element, includes
// specific key, app, env attributes, and other fields to display
// the element's version status.
type ElementMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	App string `protobuf:"bytes,2,opt,name=app,proto3" json:"app,omitempty"`
	Env string `protobuf:"bytes,3,opt,name=env,proto3" json:"env,omitempty"`
	// the latest version in all versions of the element.
	LatestVersion int32 `protobuf:"varint,4,opt,name=latestVersion,proto3" json:"latestVersion,omitempty"`
	// if there is any unpublished version, if there's any unpublished
	// version, the element can not create a new version util all versions have been
	// published,
	UnpublishedVersion int32 `protobuf:"varint,5,opt,name=unpublishedVersion,proto3" json:"unpublishedVersion,omitempty"`
	// the in-use version.
	UsingVersion int32 `protobuf:"varint,6,opt,name=usingVersion,proto3" json:"usingVersion,omitempty"`
	// the using version's fingerprint.
	UsingFingerprint string `protobuf:"bytes,7,opt,name=usingFingerprint,proto3" json:"usingFingerprint,omitempty"`
	// indicates the content type of Element's raw data
	ContentType ContentType `protobuf:"varint,8,opt,name=contentType,proto3,enum=cassem.concept.ContentType" json:"contentType,omitempty"`
}

func (x *ElementMetadata) Reset() {
	*x = ElementMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ElementMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElementMetadata) ProtoMessage() {}

func (x *ElementMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElementMetadata.ProtoReflect.Descriptor instead.
func (*ElementMetadata) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{1}
}

func (x *ElementMetadata) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ElementMetadata) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

func (x *ElementMetadata) GetEnv() string {
	if x != nil {
		return x.Env
	}
	return ""
}

func (x *ElementMetadata) GetLatestVersion() int32 {
	if x != nil {
		return x.LatestVersion
	}
	return 0
}

func (x *ElementMetadata) GetUnpublishedVersion() int32 {
	if x != nil {
		return x.UnpublishedVersion
	}
	return 0
}

func (x *ElementMetadata) GetUsingVersion() int32 {
	if x != nil {
		return x.UsingVersion
	}
	return 0
}

func (x *ElementMetadata) GetUsingFingerprint() string {
	if x != nil {
		return x.UsingFingerprint
	}
	return ""
}

func (x *ElementMetadata) GetContentType() ContentType {
	if x != nil {
		return x.ContentType
	}
	return ContentType_UNKNOWN
}

// AppMetadata contains metadata of one app, includes specific identity,
// description, and other fields to display the app's status.
type AppMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt   int64  `protobuf:"varint,3,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	// creator of the app indicates the user who created the app.
	Creator string `protobuf:"bytes,4,opt,name=creator,proto3" json:"creator,omitempty"`
	// owner of the app indicates the user who actually own this app.
	// of course, admin account owns all apps.
	Owner  string             `protobuf:"bytes,5,opt,name=owner,proto3" json:"owner,omitempty"`
	Status AppMetadata_Status `protobuf:"varint,6,opt,name=status,proto3,enum=cassem.concept.AppMetadata_Status" json:"status,omitempty"`
	// secrets is the key to acccecss the app's elements by different envs. If it's empty,
	// that means the app is public.
	Secrets map[string]string `protobuf:"bytes,7,rep,name=secrets,proto3" json:"secrets,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *AppMetadata) Reset() {
	*x = AppMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppMetadata) ProtoMessage() {}

func (x *AppMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppMetadata.ProtoReflect.Descriptor instead.
func (*AppMetadata) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{2}
}

func (x *AppMetadata) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AppMetadata) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AppMetadata) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *AppMetadata) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

func (x *AppMetadata) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *AppMetadata) GetStatus() AppMetadata_Status {
	if x != nil {
		return x.Status
	}
	return AppMetadata_INUSE
}

func (x *AppMetadata) GetSecrets() map[string]string {
	if x != nil {
		return x.Secrets
	}
	return nil
}

// ElementOperation is used to indicate the operation of one element.
type ElementOperation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// operator indicates the user who execute the operation.
	Operator       string              `protobuf:"bytes,1,opt,name=operator,proto3" json:"operator,omitempty"`
	OperatedAt     int64               `protobuf:"varint,2,opt,name=operatedAt,proto3" json:"operatedAt,omitempty"`
	OperatedKey    string              `protobuf:"bytes,3,opt,name=operatedKey,proto3" json:"operatedKey,omitempty"`
	Op             ElementOperation_Op `protobuf:"varint,4,opt,name=op,proto3,enum=cassem.concept.ElementOperation_Op" json:"op,omitempty"`
	LastVersion    int32               `protobuf:"varint,5,opt,name=lastVersion,proto3" json:"lastVersion,omitempty"`
	CurrentVersion int32               `protobuf:"varint,6,opt,name=currentVersion,proto3" json:"currentVersion,omitempty"`
	Remark         string              `protobuf:"bytes,7,opt,name=remark,proto3" json:"remark,omitempty"`
}

func (x *ElementOperation) Reset() {
	*x = ElementOperation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ElementOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElementOperation) ProtoMessage() {}

func (x *ElementOperation) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElementOperation.ProtoReflect.Descriptor instead.
func (*ElementOperation) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{3}
}

func (x *ElementOperation) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *ElementOperation) GetOperatedAt() int64 {
	if x != nil {
		return x.OperatedAt
	}
	return 0
}

func (x *ElementOperation) GetOperatedKey() string {
	if x != nil {
		return x.OperatedKey
	}
	return ""
}

func (x *ElementOperation) GetOp() ElementOperation_Op {
	if x != nil {
		return x.Op
	}
	return ElementOperation_INVALID
}

func (x *ElementOperation) GetLastVersion() int32 {
	if x != nil {
		return x.LastVersion
	}
	return 0
}

func (x *ElementOperation) GetCurrentVersion() int32 {
	if x != nil {
		return x.CurrentVersion
	}
	return 0
}

func (x *ElementOperation) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

// Instance describes client instance.
type Instance struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId           string               `protobuf:"bytes,1,opt,name=clientId,proto3" json:"clientId,omitempty"`
	AgentId            string               `protobuf:"bytes,2,opt,name=agentId,proto3" json:"agentId,omitempty"`
	ClientIp           string               `protobuf:"bytes,3,opt,name=clientIp,proto3" json:"clientIp,omitempty"`
	Watching           []*Instance_Watching `protobuf:"bytes,4,rep,name=watching,proto3" json:"watching,omitempty"`
	LastRenewTimestamp int64                `protobuf:"varint,5,opt,name=lastRenewTimestamp,proto3" json:"lastRenewTimestamp,omitempty"`
}

func (x *Instance) Reset() {
	*x = Instance{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Instance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Instance) ProtoMessage() {}

func (x *Instance) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Instance.ProtoReflect.Descriptor instead.
func (*Instance) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{4}
}

func (x *Instance) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *Instance) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Instance) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *Instance) GetWatching() []*Instance_Watching {
	if x != nil {
		return x.Watching
	}
	return nil
}

func (x *Instance) GetLastRenewTimestamp() int64 {
	if x != nil {
		return x.LastRenewTimestamp
	}
	return 0
}

// AgentInstance describes agent node instance attributes.
type AgentInstance struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// agentId is the unique identifier for agent.
	AgentId string `protobuf:"bytes,1,opt,name=agentId,proto3" json:"agentId,omitempty"`
	Addr    string `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	// annotations contains the some custom label and value of AgentInstance.
	Annotations map[string]string `protobuf:"bytes,3,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *AgentInstance) Reset() {
	*x = AgentInstance{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgentInstance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentInstance) ProtoMessage() {}

func (x *AgentInstance) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentInstance.ProtoReflect.Descriptor instead.
func (*AgentInstance) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{5}
}

func (x *AgentInstance) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentInstance) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *AgentInstance) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

type AgentInstanceChange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ins *AgentInstance `protobuf:"bytes,1,opt,name=ins,proto3" json:"ins,omitempty"`
	Op  ChangeOp       `protobuf:"varint,2,opt,name=op,proto3,enum=cassem.concept.ChangeOp" json:"op,omitempty"`
}

func (x *AgentInstanceChange) Reset() {
	*x = AgentInstanceChange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgentInstanceChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentInstanceChange) ProtoMessage() {}

func (x *AgentInstanceChange) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentInstanceChange.ProtoReflect.Descriptor instead.
func (*AgentInstanceChange) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{6}
}

func (x *AgentInstanceChange) GetIns() *AgentInstance {
	if x != nil {
		return x.Ins
	}
	return nil
}

func (x *AgentInstanceChange) GetOp() ChangeOp {
	if x != nil {
		return x.Op
	}
	return ChangeOp_UNDEFINED
}

type Instance_Watching struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	App       string   `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	Env       string   `protobuf:"bytes,2,opt,name=env,proto3" json:"env,omitempty"`
	WatchKeys []string `protobuf:"bytes,3,rep,name=watchKeys,proto3" json:"watchKeys,omitempty"`
}

func (x *Instance_Watching) Reset() {
	*x = Instance_Watching{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Instance_Watching) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Instance_Watching) ProtoMessage() {}

func (x *Instance_Watching) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Instance_Watching.ProtoReflect.Descriptor instead.
func (*Instance_Watching) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{4, 0}
}

func (x *Instance_Watching) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

func (x *Instance_Watching) GetEnv() string {
	if x != nil {
		return x.Env
	}
	return ""
}

func (x *Instance_Watching) GetWatchKeys() []string {
	if x != nil {
		return x.WatchKeys
	}
	return nil
}

var File_types_proto protoreflect.FileDescriptor

var file_types_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x63,
	0x61, 0x73, 0x73, 0x65, 0x6d, 0x2e, 0x63, 0x6f, 0x6e, 0x63, 0x65, 0x70, 0x74, 0x22, 0x90, 0x01,
	0x0a, 0x07, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x3b, 0x0a, 0x08, 0x6d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x63, 0x61,
	0x73, 0x73, 0x65, 0x6d, 0x2e, 0x63, 0x6f, 0x6e, 0x63, 0x65, 0x70, 0x74, 0x2e, 0x45, 0x6c, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x61, 0x77, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x03, 0x72, 0x61, 0x77, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x64,
	0x22, 0xac, 0x02, 0x0a, 0x0f, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x70, 0x70, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x61, 0x70, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x6e, 0x76, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x6e, 0x76, 0x12, 0x24, 0x0a, 0x0d, 0x6c, 0x61,
	0x74, 0x65, 0x73, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0d, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x12, 0x2e, 0x0a, 0x12, 0x75, 0x6e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x64, 0x56,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x12, 0x75, 0x6e,
	0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x64, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x12, 0x22, 0x0a, 0x0c, 0x75, 0x73, 0x69, 0x6e, 0x67, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x75, 0x73, 0x69, 0x6e, 0x67, 0x56, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x12, 0x2a, 0x0a, 0x10, 0x75, 0x73, 0x69, 0x6e, 0x67, 0x46, 0x69, 0x6e,
	0x67, 0x65, 0x72, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10,
	0x75, 0x73, 0x69, 0x6e, 0x67, 0x46, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x70, 0x72, 0x69, 0x6e, 0x74,
	0x12, 0x3d, 0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x63, 0x61, 0x73, 0x73, 0x65, 0x6d, 0x2e, 0x63,
	0x6f, 0x6e, 0x63, 0x65, 0x70, 0x74, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x22,
	0xee, 0x02, 0x0a, 0x0b, 0x41, 0x70, 0x70, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12,
	0x18, 0x0a, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x77, 0x6e,
	0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x12,
	0x3a, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x22, 0x2e, 0x63, 0x61, 0x73, 0x73, 0x65, 0x6d, 0x2e, 0x63, 0x6f, 0x6e, 0x63, 0x65, 0x70, 0x74,
	0x2e, 0x41, 0x70, 0x70, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x42, 0x0a, 0x07, 0x73,
	0x65, 0x63, 0x72, 0x65, 0x74, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x63,
	0x61, 0x73, 0x73, 0x65, 0x6d, 0x2e, 0x63, 0x6f, 0x6e, 0x63, 0x65, 0x70, 0x74, 0x2e, 0x41, 0x70,
	0x70, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74,
	0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x73, 0x1a,
	0x3a, 0x0a, 0x0c, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x23, 0x0a, 0x06, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x09, 0x0a, 0x05, 0x49, 0x4e, 0x55, 0x53, 0x45, 0x10, 0x00,
	0x12, 0x0e, 0x0a, 0x0a, 0x44, 0x45, 0x50, 0x52, 0x45, 0x43, 0x41, 0x54, 0x45, 0x44, 0x10, 0x01,
	0x22, 0xbb, 0x02, 0x0a, 0x10, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x4f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f,
	0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x41,
	0x74, 0x12, 0x20, 0x0a, 0x0b, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x4b, 0x65, 0x79,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64,
	0x4b, 0x65, 0x79, 0x12, 0x33, 0x0a, 0x02, 0x6f, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x23, 0x2e, 0x63, 0x61, 0x73, 0x73, 0x65, 0x6d, 0x2e, 0x63, 0x6f, 0x6e, 0x63, 0x65, 0x70, 0x74,
	0x2e, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x4f, 0x70, 0x52, 0x02, 0x6f, 0x70, 0x12, 0x20, 0x0a, 0x0b, 0x6c, 0x61, 0x73, 0x74,
	0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x6c,
	0x61, 0x73, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x26, 0x0a, 0x0e, 0x63, 0x75,
	0x72, 0x72, 0x65, 0x6e, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0e, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x22, 0x32, 0x0a, 0x02, 0x4f, 0x70,
	0x12, 0x0b, 0x0a, 0x07, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x10, 0x00, 0x12, 0x07, 0x0a,
	0x03, 0x53, 0x45, 0x54, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x55, 0x4e, 0x53, 0x45, 0x54, 0x10,
	0x02, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x55, 0x42, 0x4c, 0x49, 0x53, 0x48, 0x10, 0x03, 0x22, 0x99,
	0x02, 0x0a, 0x08, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x67, 0x65, 0x6e, 0x74,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49,
	0x64, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x70, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x70, 0x12, 0x3d, 0x0a,
	0x08, 0x77, 0x61, 0x74, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x21, 0x2e, 0x63, 0x61, 0x73, 0x73, 0x65, 0x6d, 0x2e, 0x63, 0x6f, 0x6e, 0x63, 0x65, 0x70, 0x74,
	0x2e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x57, 0x61, 0x74, 0x63, 0x68, 0x69,
	0x6e, 0x67, 0x52, 0x08, 0x77, 0x61, 0x74, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x12, 0x2e, 0x0a, 0x12,
	0x6c, 0x61, 0x73, 0x74, 0x52, 0x65, 0x6e, 0x65, 0x77, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x12, 0x6c, 0x61, 0x73, 0x74, 0x52, 0x65,
	0x6e, 0x65, 0x77, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x1a, 0x4c, 0x0a, 0x08,
	0x57, 0x61, 0x74, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x70, 0x70, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x61, 0x70, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x6e,
	0x76, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x6e, 0x76, 0x12, 0x1c, 0x0a, 0x09,
	0x77, 0x61, 0x74, 0x63, 0x68, 0x4b, 0x65, 0x79, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x09, 0x77, 0x61, 0x74, 0x63, 0x68, 0x4b, 0x65, 0x79, 0x73, 0x22, 0xcf, 0x01, 0x0a, 0x0d, 0x41,
	0x67, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x61, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61,
	0x67, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x64, 0x64, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x64, 0x64, 0x72, 0x12, 0x50, 0x0a, 0x0b, 0x61, 0x6e,
	0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x2e, 0x2e, 0x63, 0x61, 0x73, 0x73, 0x65, 0x6d, 0x2e, 0x63, 0x6f, 0x6e, 0x63, 0x65, 0x70, 0x74,
	0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x41,
	0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52,
	0x0b, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x1a, 0x3e, 0x0a, 0x10,
	0x41, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x70, 0x0a, 0x13,
	0x41, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x43, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x12, 0x2f, 0x0a, 0x03, 0x69, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1d, 0x2e, 0x63, 0x61, 0x73, 0x73, 0x65, 0x6d, 0x2e, 0x63, 0x6f, 0x6e, 0x63, 0x65, 0x70,
	0x74, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x52,
	0x03, 0x69, 0x6e, 0x73, 0x12, 0x28, 0x0a, 0x02, 0x6f, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x18, 0x2e, 0x63, 0x61, 0x73, 0x73, 0x65, 0x6d, 0x2e, 0x63, 0x6f, 0x6e, 0x63, 0x65, 0x70,
	0x74, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x4f, 0x70, 0x52, 0x02, 0x6f, 0x70, 0x2a, 0x46,
	0x0a, 0x0b, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a,
	0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x4a, 0x53,
	0x4f, 0x4e, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x54, 0x4f, 0x4d, 0x4c, 0x10, 0x02, 0x12, 0x07,
	0x0a, 0x03, 0x49, 0x4e, 0x49, 0x10, 0x03, 0x12, 0x0d, 0x0a, 0x09, 0x50, 0x4c, 0x41, 0x49, 0x4e,
	0x54, 0x45, 0x58, 0x54, 0x10, 0x04, 0x2a, 0x3a, 0x0a, 0x08, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x4f, 0x70, 0x12, 0x0d, 0x0a, 0x09, 0x55, 0x4e, 0x44, 0x45, 0x46, 0x49, 0x4e, 0x45, 0x44, 0x10,
	0x00, 0x12, 0x07, 0x0a, 0x03, 0x4e, 0x45, 0x57, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x55, 0x50,
	0x44, 0x41, 0x54, 0x45, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x45,
	0x10, 0x03, 0x42, 0x2e, 0x5a, 0x2c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x79, 0x65, 0x71, 0x6f, 0x77, 0x6e, 0x2f, 0x63, 0x61, 0x73, 0x73, 0x65, 0x6d, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x63, 0x6f, 0x6e, 0x63, 0x65, 0x70, 0x74, 0x3b, 0x63, 0x6f, 0x6e, 0x63, 0x65,
	0x70, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_types_proto_rawDescOnce sync.Once
	file_types_proto_rawDescData = file_types_proto_rawDesc
)

func file_types_proto_rawDescGZIP() []byte {
	file_types_proto_rawDescOnce.Do(func() {
		file_types_proto_rawDescData = protoimpl.X.CompressGZIP(file_types_proto_rawDescData)
	})
	return file_types_proto_rawDescData
}

var file_types_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_types_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_types_proto_goTypes = []interface{}{
	(ContentType)(0),            // 0: cassem.concept.ContentType
	(ChangeOp)(0),               // 1: cassem.concept.ChangeOp
	(AppMetadata_Status)(0),     // 2: cassem.concept.AppMetadata.Status
	(ElementOperation_Op)(0),    // 3: cassem.concept.ElementOperation.Op
	(*Element)(nil),             // 4: cassem.concept.Element
	(*ElementMetadata)(nil),     // 5: cassem.concept.ElementMetadata
	(*AppMetadata)(nil),         // 6: cassem.concept.AppMetadata
	(*ElementOperation)(nil),    // 7: cassem.concept.ElementOperation
	(*Instance)(nil),            // 8: cassem.concept.Instance
	(*AgentInstance)(nil),       // 9: cassem.concept.AgentInstance
	(*AgentInstanceChange)(nil), // 10: cassem.concept.AgentInstanceChange
	nil,                         // 11: cassem.concept.AppMetadata.SecretsEntry
	(*Instance_Watching)(nil),   // 12: cassem.concept.Instance.Watching
	nil,                         // 13: cassem.concept.AgentInstance.AnnotationsEntry
}
var file_types_proto_depIdxs = []int32{
	5,  // 0: cassem.concept.Element.metadata:type_name -> cassem.concept.ElementMetadata
	0,  // 1: cassem.concept.ElementMetadata.contentType:type_name -> cassem.concept.ContentType
	2,  // 2: cassem.concept.AppMetadata.status:type_name -> cassem.concept.AppMetadata.Status
	11, // 3: cassem.concept.AppMetadata.secrets:type_name -> cassem.concept.AppMetadata.SecretsEntry
	3,  // 4: cassem.concept.ElementOperation.op:type_name -> cassem.concept.ElementOperation.Op
	12, // 5: cassem.concept.Instance.watching:type_name -> cassem.concept.Instance.Watching
	13, // 6: cassem.concept.AgentInstance.annotations:type_name -> cassem.concept.AgentInstance.AnnotationsEntry
	9,  // 7: cassem.concept.AgentInstanceChange.ins:type_name -> cassem.concept.AgentInstance
	1,  // 8: cassem.concept.AgentInstanceChange.op:type_name -> cassem.concept.ChangeOp
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_types_proto_init() }
func file_types_proto_init() {
	if File_types_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_types_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Element); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ElementMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ElementOperation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Instance); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgentInstance); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgentInstanceChange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Instance_Watching); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_types_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_proto_goTypes,
		DependencyIndexes: file_types_proto_depIdxs,
		EnumInfos:         file_types_proto_enumTypes,
		MessageInfos:      file_types_proto_msgTypes,
	}.Build()
	File_types_proto = out.File
	file_types_proto_rawDesc = nil
	file_types_proto_goTypes = nil
	file_types_proto_depIdxs = nil
}
