services:
  cassemkv1:
    image: yeqown/cassemkv:${IMAGE_TAG:-test}
    ports:
      - "127.0.0.1:2021:2021"
    volumes:
      - ${CASSEM_EXAMPLES_DIR:-.}/cassemkv:/app/cassemkv/configs:ro
      - cassemkv1-data:/app/cassemkv/storage
    command:
      - ./cassemkv
      - --conf
      - ./configs/cassemkv.toml
      - --listen-addr
      - 0.0.0.0:2021
      - --advertise-addr
      - 127.0.0.1:2021
      - --raft.cluster
      - http://cassemkv1:3021,http://cassemkv2:3022,http://cassemkv3:3023
      - --raft.bind
      - http://cassemkv1:3021
      - --storage
      - ./storage

  cassemkv2:
    image: yeqown/cassemkv:${IMAGE_TAG:-test}
    ports:
      - "127.0.0.1:2022:2021"
    volumes:
      - ${CASSEM_EXAMPLES_DIR:-.}/cassemkv:/app/cassemkv/configs:ro
      - cassemkv2-data:/app/cassemkv/storage
    command:
      - ./cassemkv
      - --conf
      - ./configs/cassemkv.toml
      - --listen-addr
      - 0.0.0.0:2021
      - --advertise-addr
      - 127.0.0.1:2022
      - --raft.cluster
      - http://cassemkv1:3021,http://cassemkv2:3022,http://cassemkv3:3023
      - --raft.bind
      - http://cassemkv2:3022
      - --storage
      - ./storage

  cassemkv3:
    image: yeqown/cassemkv:${IMAGE_TAG:-test}
    ports:
      - "127.0.0.1:2023:2021"
    volumes:
      - ${CASSEM_EXAMPLES_DIR:-.}/cassemkv:/app/cassemkv/configs:ro
      - cassemkv3-data:/app/cassemkv/storage
    command:
      - ./cassemkv
      - --conf
      - ./configs/cassemkv.toml
      - --listen-addr
      - 0.0.0.0:2021
      - --advertise-addr
      - 127.0.0.1:2023
      - --raft.cluster
      - http://cassemkv1:3021,http://cassemkv2:3022,http://cassemkv3:3023
      - --raft.bind
      - http://cassemkv3:3023
      - --storage
      - ./storage

  cassemadm:
    image: yeqown/cassemadm:${IMAGE_TAG:-test}
    depends_on:
      - cassemkv1
      - cassemkv2
      - cassemkv3
    ports:
      - "127.0.0.1:20218:20218"
    volumes:
      - ${CASSEM_EXAMPLES_DIR:-.}/cassemadm:/app/cassemadm/configs:ro

  cassemagent:
    image: yeqown/cassemagent:${IMAGE_TAG:-test}
    hostname: cassemagent
    depends_on:
      - cassemkv1
      - cassemkv2
      - cassemkv3
    ports:
      - "127.0.0.1:20219:20219"
    volumes:
      - ${CASSEM_EXAMPLES_DIR:-.}/cassemagent:/app/cassemagent/configs:ro

volumes:
  cassemkv1-data:
  cassemkv2-data:
  cassemkv3-data:
