// Code generated by "stringer -type=ChangeOp"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OpSet-1]
	_ = x[OpUnset-2]
}

const _Op_name = "OpSetOpUnset"

var _Op_index = [...]uint8{0, 5, 12}

func (i ChangeOp) String() string {
	i -= 1
	if i >= ChangeOp(len(_Op_index)-1) {
		return "ChangeOp(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Op_name[_Op_index[i]:_Op_index[i+1]]
}
