debug = false
[persistence]
    [persistence.bbolt]
            dir       = "./debugdata/d3"
            db        = "cassemdb.kv"

[server]
    [server.http]
        addr    = ":2023"
    [server.raft]
        base = "./debugdata/d3"
        bind = "127.0.0.1:3023"
        serverId = "d3"
        join = ["127.0.0.1:2021"]