debug = false
[persistence]
    [persistence.bbolt]
            dir       = "./debugdata/d1"
            db        = "cassemdb.kv"

[server]
    [server.http]
        addr    = ":2021"
    [server.raft]
        base = "./debugdata/d1"
        bind = "127.0.0.1:3021"
        serverId = "d1"
        join = []
