// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EntityType int32

const (
	EntityType_UNKNOWN EntityType = 0
	EntityType_ELT     EntityType = 1
	EntityType_DIR     EntityType = 2
)

var EntityType_name = map[int32]string{
	0: "UNKNOWN",
	1: "ELT",
	2: "DIR",
}

var EntityType_value = map[string]int32{
	"UNKNOWN": 0,
	"ELT":     1,
	"DIR":     2,
}

func (x EntityType) String() string {
	return proto.EnumName(EntityType_name, int32(x))
}

func (EntityType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

type Change_ChangeOp int32

const (
	Change_Invalid Change_ChangeOp = 0
	Change_Set     Change_ChangeOp = 1
	Change_Unset   Change_ChangeOp = 2
)

var Change_ChangeOp_name = map[int32]string{
	0: "Invalid",
	1: "Set",
	2: "Unset",
}

var Change_ChangeOp_value = map[string]int32{
	"Invalid": 0,
	"Set":     1,
	"Unset":   2,
}

func (x Change_ChangeOp) String() string {
	return proto.EnumName(Change_ChangeOp_name, int32(x))
}

func (Change_ChangeOp) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1, 0}
}

type Entity struct {
	Fingerprint          string     `protobuf:"bytes,1,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	Key                  string     `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Val                  []byte     `protobuf:"bytes,3,opt,name=val,proto3" json:"val,omitempty"`
	CreatedAt            int64      `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            int64      `protobuf:"varint,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Ttl                  int32      `protobuf:"varint,6,opt,name=ttl,proto3" json:"ttl,omitempty"`
	Typ                  EntityType `protobuf:"varint,7,opt,name=typ,proto3,enum=cassem.db.EntityType" json:"typ,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Entity) Reset()         { *m = Entity{} }
func (m *Entity) String() string { return proto.CompactTextString(m) }
func (*Entity) ProtoMessage()    {}
func (*Entity) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *Entity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Entity.Unmarshal(m, b)
}
func (m *Entity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Entity.Marshal(b, m, deterministic)
}
func (m *Entity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Entity.Merge(m, src)
}
func (m *Entity) XXX_Size() int {
	return xxx_messageInfo_Entity.Size(m)
}
func (m *Entity) XXX_DiscardUnknown() {
	xxx_messageInfo_Entity.DiscardUnknown(m)
}

var xxx_messageInfo_Entity proto.InternalMessageInfo

func (m *Entity) GetFingerprint() string {
	if m != nil {
		return m.Fingerprint
	}
	return ""
}

func (m *Entity) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Entity) GetVal() []byte {
	if m != nil {
		return m.Val
	}
	return nil
}

func (m *Entity) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Entity) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *Entity) GetTtl() int32 {
	if m != nil {
		return m.Ttl
	}
	return 0
}

func (m *Entity) GetTyp() EntityType {
	if m != nil {
		return m.Typ
	}
	return EntityType_UNKNOWN
}

type Change struct {
	Op                   Change_ChangeOp `protobuf:"varint,1,opt,name=op,proto3,enum=cassem.db.Change_ChangeOp" json:"op,omitempty"`
	Key                  string          `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Last                 *Entity         `protobuf:"bytes,3,opt,name=last,proto3" json:"last,omitempty"`
	Current              *Entity         `protobuf:"bytes,4,opt,name=current,proto3" json:"current,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Change) Reset()         { *m = Change{} }
func (m *Change) String() string { return proto.CompactTextString(m) }
func (*Change) ProtoMessage()    {}
func (*Change) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *Change) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Change.Unmarshal(m, b)
}
func (m *Change) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Change.Marshal(b, m, deterministic)
}
func (m *Change) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Change.Merge(m, src)
}
func (m *Change) XXX_Size() int {
	return xxx_messageInfo_Change.Size(m)
}
func (m *Change) XXX_DiscardUnknown() {
	xxx_messageInfo_Change.DiscardUnknown(m)
}

var xxx_messageInfo_Change proto.InternalMessageInfo

func (m *Change) GetOp() Change_ChangeOp {
	if m != nil {
		return m.Op
	}
	return Change_Invalid
}

func (m *Change) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Change) GetLast() *Entity {
	if m != nil {
		return m.Last
	}
	return nil
}

func (m *Change) GetCurrent() *Entity {
	if m != nil {
		return m.Current
	}
	return nil
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type GetKVReq struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetKVReq) Reset()         { *m = GetKVReq{} }
func (m *GetKVReq) String() string { return proto.CompactTextString(m) }
func (*GetKVReq) ProtoMessage()    {}
func (*GetKVReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}

func (m *GetKVReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetKVReq.Unmarshal(m, b)
}
func (m *GetKVReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetKVReq.Marshal(b, m, deterministic)
}
func (m *GetKVReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetKVReq.Merge(m, src)
}
func (m *GetKVReq) XXX_Size() int {
	return xxx_messageInfo_GetKVReq.Size(m)
}
func (m *GetKVReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetKVReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetKVReq proto.InternalMessageInfo

func (m *GetKVReq) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type GetKVResp struct {
	Entity               *Entity  `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetKVResp) Reset()         { *m = GetKVResp{} }
func (m *GetKVResp) String() string { return proto.CompactTextString(m) }
func (*GetKVResp) ProtoMessage()    {}
func (*GetKVResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{4}
}

func (m *GetKVResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetKVResp.Unmarshal(m, b)
}
func (m *GetKVResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetKVResp.Marshal(b, m, deterministic)
}
func (m *GetKVResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetKVResp.Merge(m, src)
}
func (m *GetKVResp) XXX_Size() int {
	return xxx_messageInfo_GetKVResp.Size(m)
}
func (m *GetKVResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetKVResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetKVResp proto.InternalMessageInfo

func (m *GetKVResp) GetEntity() *Entity {
	if m != nil {
		return m.Entity
	}
	return nil
}

type GetKVsReq struct {
	Keys                 []string `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetKVsReq) Reset()         { *m = GetKVsReq{} }
func (m *GetKVsReq) String() string { return proto.CompactTextString(m) }
func (*GetKVsReq) ProtoMessage()    {}
func (*GetKVsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{5}
}

func (m *GetKVsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetKVsReq.Unmarshal(m, b)
}
func (m *GetKVsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetKVsReq.Marshal(b, m, deterministic)
}
func (m *GetKVsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetKVsReq.Merge(m, src)
}
func (m *GetKVsReq) XXX_Size() int {
	return xxx_messageInfo_GetKVsReq.Size(m)
}
func (m *GetKVsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetKVsReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetKVsReq proto.InternalMessageInfo

func (m *GetKVsReq) GetKeys() []string {
	if m != nil {
		return m.Keys
	}
	return nil
}

type GetKVsResp struct {
	Entities             []*Entity `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetKVsResp) Reset()         { *m = GetKVsResp{} }
func (m *GetKVsResp) String() string { return proto.CompactTextString(m) }
func (*GetKVsResp) ProtoMessage()    {}
func (*GetKVsResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{6}
}

func (m *GetKVsResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetKVsResp.Unmarshal(m, b)
}
func (m *GetKVsResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetKVsResp.Marshal(b, m, deterministic)
}
func (m *GetKVsResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetKVsResp.Merge(m, src)
}
func (m *GetKVsResp) XXX_Size() int {
	return xxx_messageInfo_GetKVsResp.Size(m)
}
func (m *GetKVsResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetKVsResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetKVsResp proto.InternalMessageInfo

func (m *GetKVsResp) GetEntities() []*Entity {
	if m != nil {
		return m.Entities
	}
	return nil
}

type SetKVReq struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	IsDir                bool     `protobuf:"varint,2,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	Ttl                  uint32   `protobuf:"varint,3,opt,name=ttl,proto3" json:"ttl,omitempty"`
	Val                  []byte   `protobuf:"bytes,4,opt,name=val,proto3" json:"val,omitempty"`
	Overwrite            bool     `protobuf:"varint,5,opt,name=overwrite,proto3" json:"overwrite,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetKVReq) Reset()         { *m = SetKVReq{} }
func (m *SetKVReq) String() string { return proto.CompactTextString(m) }
func (*SetKVReq) ProtoMessage()    {}
func (*SetKVReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{7}
}

func (m *SetKVReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetKVReq.Unmarshal(m, b)
}
func (m *SetKVReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetKVReq.Marshal(b, m, deterministic)
}
func (m *SetKVReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetKVReq.Merge(m, src)
}
func (m *SetKVReq) XXX_Size() int {
	return xxx_messageInfo_SetKVReq.Size(m)
}
func (m *SetKVReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SetKVReq.DiscardUnknown(m)
}

var xxx_messageInfo_SetKVReq proto.InternalMessageInfo

func (m *SetKVReq) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *SetKVReq) GetIsDir() bool {
	if m != nil {
		return m.IsDir
	}
	return false
}

func (m *SetKVReq) GetTtl() uint32 {
	if m != nil {
		return m.Ttl
	}
	return 0
}

func (m *SetKVReq) GetVal() []byte {
	if m != nil {
		return m.Val
	}
	return nil
}

func (m *SetKVReq) GetOverwrite() bool {
	if m != nil {
		return m.Overwrite
	}
	return false
}

type UnsetKVReq struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	IsDir                bool     `protobuf:"varint,2,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnsetKVReq) Reset()         { *m = UnsetKVReq{} }
func (m *UnsetKVReq) String() string { return proto.CompactTextString(m) }
func (*UnsetKVReq) ProtoMessage()    {}
func (*UnsetKVReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{8}
}

func (m *UnsetKVReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnsetKVReq.Unmarshal(m, b)
}
func (m *UnsetKVReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnsetKVReq.Marshal(b, m, deterministic)
}
func (m *UnsetKVReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnsetKVReq.Merge(m, src)
}
func (m *UnsetKVReq) XXX_Size() int {
	return xxx_messageInfo_UnsetKVReq.Size(m)
}
func (m *UnsetKVReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UnsetKVReq.DiscardUnknown(m)
}

var xxx_messageInfo_UnsetKVReq proto.InternalMessageInfo

func (m *UnsetKVReq) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *UnsetKVReq) GetIsDir() bool {
	if m != nil {
		return m.IsDir
	}
	return false
}

type WatchReq struct {
	Keys                 []string `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WatchReq) Reset()         { *m = WatchReq{} }
func (m *WatchReq) String() string { return proto.CompactTextString(m) }
func (*WatchReq) ProtoMessage()    {}
func (*WatchReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{9}
}

func (m *WatchReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WatchReq.Unmarshal(m, b)
}
func (m *WatchReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WatchReq.Marshal(b, m, deterministic)
}
func (m *WatchReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WatchReq.Merge(m, src)
}
func (m *WatchReq) XXX_Size() int {
	return xxx_messageInfo_WatchReq.Size(m)
}
func (m *WatchReq) XXX_DiscardUnknown() {
	xxx_messageInfo_WatchReq.DiscardUnknown(m)
}

var xxx_messageInfo_WatchReq proto.InternalMessageInfo

func (m *WatchReq) GetKeys() []string {
	if m != nil {
		return m.Keys
	}
	return nil
}

type TtlReq struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TtlReq) Reset()         { *m = TtlReq{} }
func (m *TtlReq) String() string { return proto.CompactTextString(m) }
func (*TtlReq) ProtoMessage()    {}
func (*TtlReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{10}
}

func (m *TtlReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TtlReq.Unmarshal(m, b)
}
func (m *TtlReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TtlReq.Marshal(b, m, deterministic)
}
func (m *TtlReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TtlReq.Merge(m, src)
}
func (m *TtlReq) XXX_Size() int {
	return xxx_messageInfo_TtlReq.Size(m)
}
func (m *TtlReq) XXX_DiscardUnknown() {
	xxx_messageInfo_TtlReq.DiscardUnknown(m)
}

var xxx_messageInfo_TtlReq proto.InternalMessageInfo

func (m *TtlReq) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type TtlResp struct {
	Ttl                  int32    `protobuf:"varint,1,opt,name=ttl,proto3" json:"ttl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TtlResp) Reset()         { *m = TtlResp{} }
func (m *TtlResp) String() string { return proto.CompactTextString(m) }
func (*TtlResp) ProtoMessage()    {}
func (*TtlResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{11}
}

func (m *TtlResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TtlResp.Unmarshal(m, b)
}
func (m *TtlResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TtlResp.Marshal(b, m, deterministic)
}
func (m *TtlResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TtlResp.Merge(m, src)
}
func (m *TtlResp) XXX_Size() int {
	return xxx_messageInfo_TtlResp.Size(m)
}
func (m *TtlResp) XXX_DiscardUnknown() {
	xxx_messageInfo_TtlResp.DiscardUnknown(m)
}

var xxx_messageInfo_TtlResp proto.InternalMessageInfo

func (m *TtlResp) GetTtl() int32 {
	if m != nil {
		return m.Ttl
	}
	return 0
}

type ExpireReq struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExpireReq) Reset()         { *m = ExpireReq{} }
func (m *ExpireReq) String() string { return proto.CompactTextString(m) }
func (*ExpireReq) ProtoMessage()    {}
func (*ExpireReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{12}
}

func (m *ExpireReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExpireReq.Unmarshal(m, b)
}
func (m *ExpireReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExpireReq.Marshal(b, m, deterministic)
}
func (m *ExpireReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExpireReq.Merge(m, src)
}
func (m *ExpireReq) XXX_Size() int {
	return xxx_messageInfo_ExpireReq.Size(m)
}
func (m *ExpireReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ExpireReq.DiscardUnknown(m)
}

var xxx_messageInfo_ExpireReq proto.InternalMessageInfo

func (m *ExpireReq) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type RangeReq struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Seek                 string   `protobuf:"bytes,2,opt,name=seek,proto3" json:"seek,omitempty"`
	Limit                int32    `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RangeReq) Reset()         { *m = RangeReq{} }
func (m *RangeReq) String() string { return proto.CompactTextString(m) }
func (*RangeReq) ProtoMessage()    {}
func (*RangeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{13}
}

func (m *RangeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RangeReq.Unmarshal(m, b)
}
func (m *RangeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RangeReq.Marshal(b, m, deterministic)
}
func (m *RangeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RangeReq.Merge(m, src)
}
func (m *RangeReq) XXX_Size() int {
	return xxx_messageInfo_RangeReq.Size(m)
}
func (m *RangeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RangeReq.DiscardUnknown(m)
}

var xxx_messageInfo_RangeReq proto.InternalMessageInfo

func (m *RangeReq) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *RangeReq) GetSeek() string {
	if m != nil {
		return m.Seek
	}
	return ""
}

func (m *RangeReq) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type RangeResp struct {
	Entities             []*Entity `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`
	HasMore              bool      `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	NextSeekKey          string    `protobuf:"bytes,3,opt,name=next_seek_key,json=nextSeekKey,proto3" json:"next_seek_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RangeResp) Reset()         { *m = RangeResp{} }
func (m *RangeResp) String() string { return proto.CompactTextString(m) }
func (*RangeResp) ProtoMessage()    {}
func (*RangeResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{14}
}

func (m *RangeResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RangeResp.Unmarshal(m, b)
}
func (m *RangeResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RangeResp.Marshal(b, m, deterministic)
}
func (m *RangeResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RangeResp.Merge(m, src)
}
func (m *RangeResp) XXX_Size() int {
	return xxx_messageInfo_RangeResp.Size(m)
}
func (m *RangeResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RangeResp.DiscardUnknown(m)
}

var xxx_messageInfo_RangeResp proto.InternalMessageInfo

func (m *RangeResp) GetEntities() []*Entity {
	if m != nil {
		return m.Entities
	}
	return nil
}

func (m *RangeResp) GetHasMore() bool {
	if m != nil {
		return m.HasMore
	}
	return false
}

func (m *RangeResp) GetNextSeekKey() string {
	if m != nil {
		return m.NextSeekKey
	}
	return ""
}

func init() {
	proto.RegisterEnum("cassem.db.EntityType", EntityType_name, EntityType_value)
	proto.RegisterEnum("cassem.db.Change_ChangeOp", Change_ChangeOp_name, Change_ChangeOp_value)
	proto.RegisterType((*Entity)(nil), "cassem.db.Entity")
	proto.RegisterType((*Change)(nil), "cassem.db.change")
	proto.RegisterType((*Empty)(nil), "cassem.db.empty")
	proto.RegisterType((*GetKVReq)(nil), "cassem.db.getKVReq")
	proto.RegisterType((*GetKVResp)(nil), "cassem.db.getKVResp")
	proto.RegisterType((*GetKVsReq)(nil), "cassem.db.getKVsReq")
	proto.RegisterType((*GetKVsResp)(nil), "cassem.db.getKVsResp")
	proto.RegisterType((*SetKVReq)(nil), "cassem.db.setKVReq")
	proto.RegisterType((*UnsetKVReq)(nil), "cassem.db.unsetKVReq")
	proto.RegisterType((*WatchReq)(nil), "cassem.db.watchReq")
	proto.RegisterType((*TtlReq)(nil), "cassem.db.ttlReq")
	proto.RegisterType((*TtlResp)(nil), "cassem.db.ttlResp")
	proto.RegisterType((*ExpireReq)(nil), "cassem.db.expireReq")
	proto.RegisterType((*RangeReq)(nil), "cassem.db.rangeReq")
	proto.RegisterType((*RangeResp)(nil), "cassem.db.rangeResp")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 709 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x95, 0xdd, 0x4e, 0xdb, 0x4a,
	0x10, 0xc7, 0xe3, 0x38, 0xfe, 0x1a, 0x0e, 0x28, 0xec, 0x01, 0x29, 0x27, 0x07, 0xda, 0x68, 0xa5,
	0xaa, 0x29, 0xa8, 0x11, 0x0a, 0xb4, 0xbd, 0xe8, 0x15, 0x2d, 0xb4, 0x42, 0xa1, 0x20, 0x99, 0x00,
	0x52, 0x6f, 0x22, 0x93, 0x4c, 0xc9, 0x2a, 0x89, 0xb3, 0xf5, 0x6e, 0x00, 0xbf, 0x52, 0x5f, 0xa4,
	0xaf, 0x55, 0xed, 0xda, 0x4e, 0x4c, 0x63, 0x2e, 0xb8, 0x62, 0x98, 0x8f, 0x9d, 0xff, 0xcc, 0xfe,
	0xbc, 0x01, 0x2f, 0xe0, 0xac, 0xc5, 0xa3, 0xa9, 0x9c, 0x12, 0xaf, 0x1f, 0x08, 0x81, 0x93, 0xd6,
	0xe0, 0x86, 0xfe, 0x36, 0xc0, 0x3e, 0x0e, 0x25, 0x93, 0x31, 0x69, 0xc0, 0xca, 0x0f, 0x16, 0xde,
	0x62, 0xc4, 0x23, 0x16, 0xca, 0x9a, 0xd1, 0x30, 0x9a, 0x9e, 0x9f, 0x77, 0x91, 0x2a, 0x98, 0x23,
	0x8c, 0x6b, 0x65, 0x1d, 0x51, 0xa6, 0xf2, 0xdc, 0x05, 0xe3, 0x9a, 0xd9, 0x30, 0x9a, 0xff, 0xf8,
	0xca, 0x24, 0xdb, 0x00, 0xfd, 0x08, 0x03, 0x89, 0x83, 0x5e, 0x20, 0x6b, 0x95, 0x86, 0xd1, 0x34,
	0x7d, 0x2f, 0xf5, 0x1c, 0x4a, 0x15, 0x9e, 0xf1, 0x41, 0x16, 0xb6, 0x92, 0x70, 0xea, 0x39, 0xd4,
	0x1d, 0xa4, 0x1c, 0xd7, 0xec, 0x86, 0xd1, 0xb4, 0x7c, 0x65, 0x92, 0xd7, 0x60, 0xca, 0x98, 0xd7,
	0x9c, 0x86, 0xd1, 0x5c, 0x6b, 0x6f, 0xb6, 0xe6, 0xca, 0x5b, 0x89, 0xea, 0x6e, 0xcc, 0xd1, 0x57,
	0x19, 0x7a, 0x92, 0xfe, 0x30, 0x08, 0x6f, 0x91, 0xec, 0x40, 0x79, 0xca, 0xf5, 0x00, 0x6b, 0xed,
	0x7a, 0xae, 0x24, 0x09, 0xb7, 0x3e, 0xeb, 0x3f, 0xe7, 0xdc, 0x2f, 0x4f, 0x79, 0xc1, 0x4c, 0xaf,
	0xa0, 0x32, 0x0e, 0x84, 0xd4, 0x43, 0xad, 0xb4, 0xd7, 0x97, 0x5a, 0xfa, 0x3a, 0x4c, 0x76, 0xc1,
	0xe9, 0xcf, 0xa2, 0x08, 0xc3, 0x64, 0xca, 0xc2, 0xcc, 0x2c, 0x83, 0xee, 0x82, 0x9b, 0x75, 0x25,
	0x2b, 0xe0, 0x9c, 0x84, 0x77, 0xc1, 0x98, 0x0d, 0xaa, 0x25, 0xe2, 0x80, 0x79, 0x81, 0xb2, 0x6a,
	0x10, 0x0f, 0xac, 0xcb, 0x50, 0xa0, 0xac, 0x96, 0xa9, 0x03, 0x16, 0x4e, 0xb8, 0x8c, 0xe9, 0x16,
	0xb8, 0xb7, 0x28, 0x3b, 0x57, 0x3e, 0xfe, 0xcc, 0x74, 0x1a, 0x73, 0x9d, 0xf4, 0x3d, 0x78, 0x69,
	0x54, 0x70, 0xf2, 0x06, 0x6c, 0xd4, 0x3d, 0x75, 0x46, 0xa1, 0x98, 0x34, 0x81, 0xbe, 0x4c, 0xeb,
	0x84, 0x3a, 0x96, 0x40, 0x65, 0x84, 0xb1, 0xa8, 0x19, 0x0d, 0xb3, 0xe9, 0xf9, 0xda, 0xa6, 0x1f,
	0x01, 0xb2, 0x04, 0xc1, 0xc9, 0x5b, 0x70, 0x75, 0x21, 0xc3, 0x24, 0xab, 0xf0, 0xec, 0x79, 0x0a,
	0x9d, 0x81, 0x2b, 0x9e, 0xd4, 0x4c, 0x36, 0xc1, 0x66, 0xa2, 0x37, 0x60, 0x91, 0x5e, 0xb8, 0xeb,
	0x5b, 0x4c, 0x1c, 0xb1, 0x28, 0xbb, 0x76, 0xb5, 0xf1, 0xd5, 0xe4, 0xda, 0x53, 0xb0, 0x2a, 0x0b,
	0xb0, 0xb6, 0xc0, 0x9b, 0xde, 0x61, 0x74, 0x1f, 0x31, 0x89, 0x1a, 0x1c, 0xd7, 0x5f, 0x38, 0xe8,
	0x3b, 0x80, 0x59, 0xf8, 0xec, 0xc6, 0xf4, 0x05, 0xb8, 0xf7, 0x81, 0xec, 0x0f, 0xf3, 0xab, 0x28,
	0xe7, 0x56, 0x51, 0x07, 0x5b, 0xca, 0x71, 0xf1, 0xfe, 0xff, 0x07, 0x47, 0xc7, 0x04, 0xcf, 0xf4,
	0x1b, 0x73, 0x6c, 0xe9, 0x36, 0x78, 0xf8, 0xc0, 0x59, 0x84, 0xc5, 0xb5, 0x5f, 0xc0, 0x8d, 0x14,
	0x0e, 0xc5, 0x62, 0x09, 0x54, 0x04, 0xe2, 0x28, 0x85, 0x52, 0xdb, 0x64, 0x03, 0xac, 0x31, 0x9b,
	0xb0, 0x04, 0x4b, 0xcb, 0x4f, 0xfe, 0xa1, 0x31, 0x78, 0xe9, 0x39, 0xcf, 0xbe, 0x29, 0xf2, 0x1f,
	0xb8, 0xc3, 0x40, 0xf4, 0x26, 0xd3, 0x08, 0xd3, 0xa5, 0x38, 0xc3, 0x40, 0x7c, 0x9b, 0x46, 0x48,
	0x28, 0xac, 0x86, 0xf8, 0x20, 0x7b, 0xaa, 0x73, 0x4f, 0x89, 0x33, 0x93, 0xc7, 0x40, 0x39, 0x2f,
	0x10, 0x47, 0x1d, 0x8c, 0x77, 0x76, 0x01, 0x16, 0x9f, 0xa0, 0x82, 0xfa, 0xf2, 0xac, 0x73, 0x76,
	0x7e, 0x7d, 0x96, 0x40, 0x7d, 0x7c, 0xda, 0xad, 0x1a, 0xca, 0x38, 0x3a, 0xf1, 0xab, 0xe5, 0xf6,
	0x2f, 0x13, 0xca, 0x9d, 0x2b, 0x72, 0x00, 0xd6, 0x57, 0x75, 0x47, 0xe4, 0xdf, 0x9c, 0xb0, 0x0c,
	0xf1, 0xfa, 0xc6, 0xb2, 0x53, 0x70, 0x5a, 0x22, 0x1f, 0xc0, 0xd6, 0x55, 0x82, 0x2c, 0x65, 0x28,
	0x86, 0xeb, 0x9b, 0x05, 0x5e, 0x5d, 0xb8, 0x07, 0xd6, 0xc5, 0x52, 0xbb, 0x0c, 0x92, 0x7a, 0x35,
	0xe7, 0x4c, 0xbe, 0xb7, 0x12, 0x39, 0x00, 0xe7, 0x32, 0xc1, 0x88, 0xe4, 0x4f, 0x5d, 0xa0, 0x55,
	0x58, 0xb5, 0x0f, 0xd6, 0xb5, 0xa2, 0xe8, 0x51, 0x9f, 0x8c, 0xab, 0xfa, 0xfa, 0xd2, 0x0b, 0x44,
	0x4b, 0x7b, 0x06, 0x69, 0x81, 0xd9, 0xed, 0x9e, 0x92, 0x7c, 0x34, 0x41, 0xad, 0x4e, 0xfe, 0x76,
	0xe9, 0x61, 0xda, 0x60, 0x1f, 0x6b, 0xa2, 0x1e, 0x6d, 0x61, 0x0e, 0xd9, 0x13, 0xe3, 0x58, 0xbe,
	0x7e, 0x11, 0xf3, 0xc2, 0x32, 0xf0, 0x1e, 0xed, 0x7b, 0x4e, 0x11, 0x2d, 0x7d, 0xb2, 0xbe, 0x9b,
	0x01, 0x67, 0x37, 0xb6, 0xfe, 0xb1, 0xd8, 0xff, 0x13, 0x00, 0x00, 0xff, 0xff, 0x00, 0x0f, 0xea,
	0xa6, 0x39, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// KVClient is the client API for KV service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type KVClient interface {
	GetKV(ctx context.Context, in *GetKVReq, opts ...grpc.CallOption) (*GetKVResp, error)
	GetKVs(ctx context.Context, in *GetKVsReq, opts ...grpc.CallOption) (*GetKVsResp, error)
	SetKV(ctx context.Context, in *SetKVReq, opts ...grpc.CallOption) (*Empty, error)
	UnsetKV(ctx context.Context, in *UnsetKVReq, opts ...grpc.CallOption) (*Empty, error)
	// Watch will rev a stream response in client.
	Watch(ctx context.Context, in *WatchReq, opts ...grpc.CallOption) (KV_WatchClient, error)
	TTL(ctx context.Context, in *TtlReq, opts ...grpc.CallOption) (*TtlResp, error)
	Expire(ctx context.Context, in *ExpireReq, opts ...grpc.CallOption) (*Empty, error)
	Range(ctx context.Context, in *RangeReq, opts ...grpc.CallOption) (*RangeResp, error)
}

type kVClient struct {
	cc *grpc.ClientConn
}

func NewKVClient(cc *grpc.ClientConn) KVClient {
	return &kVClient{cc}
}

func (c *kVClient) GetKV(ctx context.Context, in *GetKVReq, opts ...grpc.CallOption) (*GetKVResp, error) {
	out := new(GetKVResp)
	err := c.cc.Invoke(ctx, "/cassem.db.KV/GetKV", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kVClient) GetKVs(ctx context.Context, in *GetKVsReq, opts ...grpc.CallOption) (*GetKVsResp, error) {
	out := new(GetKVsResp)
	err := c.cc.Invoke(ctx, "/cassem.db.KV/GetKVs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kVClient) SetKV(ctx context.Context, in *SetKVReq, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/cassem.db.KV/SetKV", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kVClient) UnsetKV(ctx context.Context, in *UnsetKVReq, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/cassem.db.KV/UnsetKV", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kVClient) Watch(ctx context.Context, in *WatchReq, opts ...grpc.CallOption) (KV_WatchClient, error) {
	stream, err := c.cc.NewStream(ctx, &_KV_serviceDesc.Streams[0], "/cassem.db.KV/Watch", opts...)
	if err != nil {
		return nil, err
	}
	x := &kVWatchClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type KV_WatchClient interface {
	Recv() (*Change, error)
	grpc.ClientStream
}

type kVWatchClient struct {
	grpc.ClientStream
}

func (x *kVWatchClient) Recv() (*Change, error) {
	m := new(Change)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *kVClient) TTL(ctx context.Context, in *TtlReq, opts ...grpc.CallOption) (*TtlResp, error) {
	out := new(TtlResp)
	err := c.cc.Invoke(ctx, "/cassem.db.KV/TTL", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kVClient) Expire(ctx context.Context, in *ExpireReq, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/cassem.db.KV/Expire", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kVClient) Range(ctx context.Context, in *RangeReq, opts ...grpc.CallOption) (*RangeResp, error) {
	out := new(RangeResp)
	err := c.cc.Invoke(ctx, "/cassem.db.KV/Range", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KVServer is the server API for KV service.
type KVServer interface {
	GetKV(context.Context, *GetKVReq) (*GetKVResp, error)
	GetKVs(context.Context, *GetKVsReq) (*GetKVsResp, error)
	SetKV(context.Context, *SetKVReq) (*Empty, error)
	UnsetKV(context.Context, *UnsetKVReq) (*Empty, error)
	// Watch will rev a stream response in client.
	Watch(*WatchReq, KV_WatchServer) error
	TTL(context.Context, *TtlReq) (*TtlResp, error)
	Expire(context.Context, *ExpireReq) (*Empty, error)
	Range(context.Context, *RangeReq) (*RangeResp, error)
}

// UnimplementedKVServer can be embedded to have forward compatible implementations.
type UnimplementedKVServer struct {
}

func (*UnimplementedKVServer) GetKV(ctx context.Context, req *GetKVReq) (*GetKVResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetKV not implemented")
}
func (*UnimplementedKVServer) GetKVs(ctx context.Context, req *GetKVsReq) (*GetKVsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetKVs not implemented")
}
func (*UnimplementedKVServer) SetKV(ctx context.Context, req *SetKVReq) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetKV not implemented")
}
func (*UnimplementedKVServer) UnsetKV(ctx context.Context, req *UnsetKVReq) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnsetKV not implemented")
}
func (*UnimplementedKVServer) Watch(req *WatchReq, srv KV_WatchServer) error {
	return status.Errorf(codes.Unimplemented, "method Watch not implemented")
}
func (*UnimplementedKVServer) TTL(ctx context.Context, req *TtlReq) (*TtlResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TTL not implemented")
}
func (*UnimplementedKVServer) Expire(ctx context.Context, req *ExpireReq) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Expire not implemented")
}
func (*UnimplementedKVServer) Range(ctx context.Context, req *RangeReq) (*RangeResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Range not implemented")
}

func RegisterKVServer(s *grpc.Server, srv KVServer) {
	s.RegisterService(&_KV_serviceDesc, srv)
}

func _KV_GetKV_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKVReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVServer).GetKV(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cassem.db.KV/GetKV",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVServer).GetKV(ctx, req.(*GetKVReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _KV_GetKVs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKVsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVServer).GetKVs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cassem.db.KV/GetKVs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVServer).GetKVs(ctx, req.(*GetKVsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _KV_SetKV_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetKVReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVServer).SetKV(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cassem.db.KV/SetKV",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVServer).SetKV(ctx, req.(*SetKVReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _KV_UnsetKV_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnsetKVReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVServer).UnsetKV(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cassem.db.KV/UnsetKV",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVServer).UnsetKV(ctx, req.(*UnsetKVReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _KV_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KVServer).Watch(m, &kVWatchServer{stream})
}

type KV_WatchServer interface {
	Send(*Change) error
	grpc.ServerStream
}

type kVWatchServer struct {
	grpc.ServerStream
}

func (x *kVWatchServer) Send(m *Change) error {
	return x.ServerStream.SendMsg(m)
}

func _KV_TTL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TtlReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVServer).TTL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cassem.db.KV/TTL",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVServer).TTL(ctx, req.(*TtlReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _KV_Expire_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExpireReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVServer).Expire(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cassem.db.KV/Expire",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVServer).Expire(ctx, req.(*ExpireReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _KV_Range_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RangeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVServer).Range(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cassem.db.KV/Range",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVServer).Range(ctx, req.(*RangeReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _KV_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cassem.db.KV",
	HandlerType: (*KVServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetKV",
			Handler:    _KV_GetKV_Handler,
		},
		{
			MethodName: "GetKVs",
			Handler:    _KV_GetKVs_Handler,
		},
		{
			MethodName: "SetKV",
			Handler:    _KV_SetKV_Handler,
		},
		{
			MethodName: "UnsetKV",
			Handler:    _KV_UnsetKV_Handler,
		},
		{
			MethodName: "TTL",
			Handler:    _KV_TTL_Handler,
		},
		{
			MethodName: "Expire",
			Handler:    _KV_Expire_Handler,
		},
		{
			MethodName: "Range",
			Handler:    _KV_Range_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _KV_Watch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api.proto",
}
