// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cassemdb.raft.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LogEntry_Action int32

const (
	LogEntry_UNKNOWN      LogEntry_Action = 0
	LogEntry_Set          LogEntry_Action = 1
	LogEntry_ChangeSpread LogEntry_Action = 2
)

var LogEntry_Action_name = map[int32]string{
	0: "UNKNOWN",
	1: "Set",
	2: "ChangeSpread",
}

var LogEntry_Action_value = map[string]int32{
	"UNKNOWN":      0,
	"Set":          1,
	"ChangeSpread": 2,
}

func (x LogEntry_Action) String() string {
	return proto.EnumName(LogEntry_Action_name, int32(x))
}

func (LogEntry_Action) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a6d703148a4047e2, []int{0, 0}
}

type LogEntry struct {
	// action indicates what's the format of data dose the log entry contains.
	Action               LogEntry_Action `protobuf:"varint,1,opt,name=action,proto3,enum=cassem.db.LogEntry_Action" json:"action,omitempty"`
	Command              []byte          `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	CreatedAt            int64           `protobuf:"varint,3,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *LogEntry) Reset()         { *m = LogEntry{} }
func (m *LogEntry) String() string { return proto.CompactTextString(m) }
func (*LogEntry) ProtoMessage()    {}
func (*LogEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_a6d703148a4047e2, []int{0}
}

func (m *LogEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogEntry.Unmarshal(m, b)
}
func (m *LogEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogEntry.Marshal(b, m, deterministic)
}
func (m *LogEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogEntry.Merge(m, src)
}
func (m *LogEntry) XXX_Size() int {
	return xxx_messageInfo_LogEntry.Size(m)
}
func (m *LogEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_LogEntry.DiscardUnknown(m)
}

var xxx_messageInfo_LogEntry proto.InternalMessageInfo

func (m *LogEntry) GetAction() LogEntry_Action {
	if m != nil {
		return m.Action
	}
	return LogEntry_UNKNOWN
}

func (m *LogEntry) GetCommand() []byte {
	if m != nil {
		return m.Command
	}
	return nil
}

func (m *LogEntry) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

type SetCommand struct {
	DeleteKey            string   `protobuf:"bytes,1,opt,name=deleteKey,proto3" json:"deleteKey,omitempty"`
	IsDir                bool     `protobuf:"varint,2,opt,name=isDir,proto3" json:"isDir,omitempty"`
	SetKey               string   `protobuf:"bytes,3,opt,name=setKey,proto3" json:"setKey,omitempty"`
	Value                *Entity  `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetCommand) Reset()         { *m = SetCommand{} }
func (m *SetCommand) String() string { return proto.CompactTextString(m) }
func (*SetCommand) ProtoMessage()    {}
func (*SetCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_a6d703148a4047e2, []int{1}
}

func (m *SetCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetCommand.Unmarshal(m, b)
}
func (m *SetCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetCommand.Marshal(b, m, deterministic)
}
func (m *SetCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetCommand.Merge(m, src)
}
func (m *SetCommand) XXX_Size() int {
	return xxx_messageInfo_SetCommand.Size(m)
}
func (m *SetCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_SetCommand.DiscardUnknown(m)
}

var xxx_messageInfo_SetCommand proto.InternalMessageInfo

func (m *SetCommand) GetDeleteKey() string {
	if m != nil {
		return m.DeleteKey
	}
	return ""
}

func (m *SetCommand) GetIsDir() bool {
	if m != nil {
		return m.IsDir
	}
	return false
}

func (m *SetCommand) GetSetKey() string {
	if m != nil {
		return m.SetKey
	}
	return ""
}

func (m *SetCommand) GetValue() *Entity {
	if m != nil {
		return m.Value
	}
	return nil
}

type ChangeCommand struct {
	Change               *Change  `protobuf:"bytes,1,opt,name=change,proto3" json:"change,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeCommand) Reset()         { *m = ChangeCommand{} }
func (m *ChangeCommand) String() string { return proto.CompactTextString(m) }
func (*ChangeCommand) ProtoMessage()    {}
func (*ChangeCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_a6d703148a4047e2, []int{2}
}

func (m *ChangeCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeCommand.Unmarshal(m, b)
}
func (m *ChangeCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeCommand.Marshal(b, m, deterministic)
}
func (m *ChangeCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeCommand.Merge(m, src)
}
func (m *ChangeCommand) XXX_Size() int {
	return xxx_messageInfo_ChangeCommand.Size(m)
}
func (m *ChangeCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeCommand.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeCommand proto.InternalMessageInfo

func (m *ChangeCommand) GetChange() *Change {
	if m != nil {
		return m.Change
	}
	return nil
}

func init() {
	proto.RegisterEnum("cassem.db.LogEntry_Action", LogEntry_Action_name, LogEntry_Action_value)
	proto.RegisterType((*LogEntry)(nil), "cassem.db.LogEntry")
	proto.RegisterType((*SetCommand)(nil), "cassem.db.SetCommand")
	proto.RegisterType((*ChangeCommand)(nil), "cassem.db.ChangeCommand")
}

func init() { proto.RegisterFile("cassemdb.raft.proto", fileDescriptor_a6d703148a4047e2) }

var fileDescriptor_a6d703148a4047e2 = []byte{
	// 296 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0x4f, 0x4f, 0xfa, 0x30,
	0x18, 0xc7, 0x7f, 0x65, 0x3f, 0x06, 0x3c, 0xa0, 0x99, 0xd5, 0x98, 0x85, 0x78, 0x58, 0x76, 0x71,
	0x5e, 0x1a, 0x83, 0x37, 0x6f, 0x88, 0x9c, 0x30, 0x98, 0x94, 0x18, 0x13, 0x6f, 0x65, 0x7d, 0xc4,
	0x26, 0xb0, 0x2d, 0xdd, 0xa3, 0x09, 0x47, 0xdf, 0x8d, 0x2f, 0xd3, 0xd8, 0x02, 0xd3, 0xe3, 0xf7,
	0xdf, 0x93, 0x4f, 0x0b, 0xa7, 0xb9, 0xaa, 0x6b, 0xdc, 0xe8, 0xa5, 0xb0, 0xea, 0x95, 0x44, 0x65,
	0x4b, 0x2a, 0x79, 0xcf, 0x9b, 0x42, 0x2f, 0x87, 0xfc, 0x90, 0xab, 0xca, 0xf8, 0x38, 0xfd, 0x62,
	0xd0, 0x7d, 0x28, 0x57, 0xd3, 0x82, 0xec, 0x96, 0x8f, 0x20, 0x54, 0x39, 0x99, 0xb2, 0x88, 0x59,
	0xc2, 0xb2, 0xe3, 0xd1, 0x50, 0x1c, 0xc6, 0x62, 0x5f, 0x12, 0x63, 0xd7, 0x90, 0xbb, 0x26, 0x8f,
	0xa1, 0x93, 0x97, 0x9b, 0x8d, 0x2a, 0x74, 0xdc, 0x4a, 0x58, 0x36, 0x90, 0x7b, 0xc9, 0x2f, 0xa0,
	0x97, 0x5b, 0x54, 0x84, 0x7a, 0x4c, 0x71, 0x90, 0xb0, 0x2c, 0x90, 0x8d, 0x91, 0x5e, 0x43, 0xe8,
	0x2f, 0xf1, 0x3e, 0x74, 0x9e, 0xe6, 0xb3, 0xf9, 0xe3, 0xf3, 0x3c, 0xfa, 0xc7, 0x3b, 0x10, 0x2c,
	0x90, 0x22, 0xc6, 0x23, 0x18, 0x4c, 0xde, 0x54, 0xb1, 0xc2, 0x45, 0x65, 0x51, 0xe9, 0xa8, 0x95,
	0x7e, 0x32, 0x80, 0x05, 0xd2, 0xa4, 0x39, 0xaf, 0x71, 0x8d, 0x84, 0x33, 0xdc, 0x3a, 0xde, 0x9e,
	0x6c, 0x0c, 0x7e, 0x06, 0x6d, 0x53, 0xdf, 0x1b, 0xeb, 0xa0, 0xba, 0xd2, 0x0b, 0x7e, 0x0e, 0x61,
	0x8d, 0xf4, 0x33, 0x08, 0xdc, 0x60, 0xa7, 0xf8, 0x25, 0xb4, 0x3f, 0xd4, 0xfa, 0x1d, 0xe3, 0xff,
	0x09, 0xcb, 0xfa, 0xa3, 0x93, 0x5f, 0xef, 0x9e, 0x16, 0x64, 0x68, 0x2b, 0x7d, 0x9e, 0xde, 0xc2,
	0x91, 0xa7, 0xda, 0x53, 0x5c, 0x41, 0x98, 0x3b, 0xc3, 0x21, 0xfc, 0x9d, 0xfa, 0xa6, 0xdc, 0x15,
	0xee, 0xda, 0x2f, 0x81, 0xaa, 0xcc, 0x32, 0x74, 0x1f, 0x7f, 0xf3, 0x1d, 0x00, 0x00, 0xff, 0xff,
	0x3a, 0x0e, 0xa5, 0x78, 0xae, 0x01, 0x00, 0x00,
}
