apiVersion: apps/v1
kind: Deployment
metadata:
  name: cassemadm
  namespace: cassem
  labels:
    app: cassemadm
spec:
  selector:
    matchLabels:
      app: cassemadm
  replicas: 1
  template:
    metadata:
      namespace: cassem
      name: cassemadm
      labels:
        app: cassemadm
    spec:
      containers:
        - name: cassemadm
          image: docker.io/yeqown/cassemadm:v0.2.1
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - "-c"
            - |
              cat /etc/cassemadm/cassemadmin.toml
              ./cassemadm -c /etc/cassemadm/cassemadmin.toml
          ports:
            - containerPort: 20218
              name: http
          volumeMounts:
            - name: cassemadm-config
              mountPath: /etc/cassemadm
              readOnly: true
          livenessProbe:
            tcpSocket:
              port: 20218
            initialDelaySeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            tcpSocket:
              port: 20218
            initialDelaySeconds: 30
            timeoutSeconds: 15
      volumes:
        - name: cassemadm-config
          configMap:
            name: cassemadm-config

# cassemadm service
---
apiVersion: v1
kind: Service
metadata:
  name: cassemadm
  namespace: cassem
  labels:
    app: cassemadm
spec:
  selector:
    app: cassemadm
  ports:
    - port: 20218
      protocol: TCP