kind: Service
apiVersion: v1
metadata:
  name: cassemdb
  labels:
    app: cassemdb
spec:
  ports:
    - port: 2021
      name: grpc
      protocol: TCP
    - port: 2022
      name: raft
      protocol: TCP
  clusterIP: None
  selector:
    app: cassemdb
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: cassem
  name: cassemdb
  labels:
      app: cassemdb
  annotations:
      app: cassemdb
spec:
  selector:
    matchLabels:
      app: cassemdb
  serviceName: "cassemdb" # cassemdb-0.cassemdb.cassem.svc.cluster.local
  replicas: 3
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
  template:
    metadata:
      namespace: cassem
      name: cassemdb
      labels:
        app: cassemdb
      annotations:
        app: cassemdb
    spec:
#      initContainers:
#        - name: prepare
#          image: docker.io/yeqown/cassemdb:v0.1
#          command:
#            - "/bin/sh"
#            - "-c"
#            - |
#              echo "hostname is: `hostname`"
#              export NODE_ID=${HOSTNAME##*-}
#              echo "nodeId=$NODE_ID"
#              cp "/etc/cassemdb/cassemdb.toml" /app/cassemdb/cassemdb.toml
#          volumeMounts:
#            - name: storage
#              mountPath: /app/cassemdb/storage
#            - name: config
#              mountPath: /etc/cassemdb
      containers:
        - name: db
          image: docker.io/yeqown/cassemdb:v0.4.2
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - "-c"
            - |
              hostname
              echo ${HOSTNAME}
              mkdir -p ./storage/${HOSTNAME##*-}
              ./cassemdb \
                -c /etc/cassemdb/cassemdb.toml \
                --endpoint=0.0.0.0:2021 \
                --raft.cluster=http://cassemdb-0.cassemdb.cassem:2022,http://cassemdb-1.cassemdb.cassem:2022,http://cassemdb-2.cassemdb.cassem:2022 \
                --raft.bind=http://${HOSTNAME}.cassemdb.cassem:2022 \
                --storage="./storage/${HOSTNAME##*-}"
          ports:
            - containerPort: 2021
              name: api
            - containerPort: 2022
              name: raft
          volumeMounts:
            - name: storage
              mountPath: /app/cassemdb/storage
            - name: config
              mountPath: /etc/cassemdb
          readinessProbe:
            tcpSocket:
              port: 2021
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 2021
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: config
          configMap:
            name: db-config
        - name: storage
          hostPath:
            path: /etc/cassemdb
            type: Directory
