kind: Service
apiVersion: v1
metadata:
  name: cassemkv
  labels:
    app: cassemkv
spec:
  ports:
    - port: 2021
      name: grpc
      protocol: TCP
    - port: 2022
      name: raft
      protocol: TCP
  clusterIP: None
  selector:
    app: cassemkv
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: cassem
  name: cassemkv
  labels:
      app: cassemkv
  annotations:
      app: cassemkv
spec:
  selector:
    matchLabels:
      app: cassemkv
  serviceName: "cassemkv" # cassemkv-0.cassemkv.cassem.svc.cluster.local
  replicas: 3
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
  template:
    metadata:
      namespace: cassem
      name: cassemkv
      labels:
        app: cassemkv
      annotations:
        app: cassemkv
    spec:
#      initContainers:
#        - name: prepare
#          image: docker.io/yeqown/cassemkv:v0.1
#          command:
#            - "/bin/sh"
#            - "-c"
#            - |
#              echo "hostname is: `hostname`"
#              export NODE_ID=${HOSTNAME##*-}
#              echo "nodeId=$NODE_ID"
#              cp "/etc/cassemkv/cassemkv.toml" /app/cassemkv/cassemkv.toml
#          volumeMounts:
#            - name: storage
#              mountPath: /app/cassemkv/storage
#            - name: config
#              mountPath: /etc/cassemkv
      containers:
        - name: db
          image: docker.io/yeqown/cassemkv:v0.4.3
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - "-c"
            - |
              hostname
              echo ${HOSTNAME}
              mkdir -p ./storage/${HOSTNAME##*-}
              ./cassemkv \
                -c /etc/cassemkv/cassemkv.toml \
                --listen-addr=0.0.0.0:2021 \
                --advertise-addr=${HOSTNAME}.cassemkv.cassem:2021 \
                --raft.cluster=http://cassemkv-0.cassemkv.cassem:2022,http://cassemkv-1.cassemkv.cassem:2022,http://cassemkv-2.cassemkv.cassem:2022 \
                --raft.bind=http://${HOSTNAME}.cassemkv.cassem:2022 \
                --storage="./storage/${HOSTNAME##*-}"
          ports:
            - containerPort: 2021
              name: api
            - containerPort: 2022
              name: raft
          volumeMounts:
            - name: storage
              mountPath: /app/cassemkv/storage
            - name: config
              mountPath: /etc/cassemkv
          readinessProbe:
            tcpSocket:
              port: 2021
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 2021
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: config
          configMap:
            name: db-config
        - name: storage
          hostPath:
            path: /etc/cassemkv
            type: Directory
