apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: cassem
  name: cassemdb
  labels:
      app: cassemdb
  annotations:
      app: cassemdb
spec:
  selector:
    matchLabels:
      app: cassemdb
  serviceName: storage
  replicas: 3
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
  template:
    metadata:
      namespace: cassem
      name: cassemdb
      labels:
        app: cassemdb
      annotations:
        app: cassemdb
    spec:
#      initContainers:
#        - name: prepare
#          image: docker.io/yeqown/cassemdb:v0.1
#          command:
#            - "/bin/sh"
#            - "-c"
#            - |
#              echo "hostname is: `hostname`"
#              export NODE_ID=${HOSTNAME##*-}
#              echo "nodeId=$NODE_ID"
#              cp "/etc/cassemdb/cassemdb.toml" /app/cassemdb/cassemdb.toml
#          volumeMounts:
#            - name: storage
#              mountPath: /app/cassemdb/storage
#            - name: config
#              mountPath: /etc/cassemdb
      containers:
        - name: db
          image: docker.io/yeqown/cassemdb:v0.2
          imagePullPolicy: Always
          command:
            - sh
            - "-c"
            - |
              sleep 30
              ./cassemdb -c ./cassemdb.toml --storage ./data --nodeId=${HOSTNAME##*-}
          ports:
            - containerPort: 2021
              name: api
          volumeMounts:
            - name: storage
              mountPath: /app/cassemdb/storage
            - name: config
              mountPath: /etc/cassemdb
          lifecycle:
            postStart:
              exec:
                command:
                  - sh
                  - "-c"
                  - |
                    cp /etc/cassemdb/cassemdb.toml /app/cassemdb/cassemdb.toml
#                    echo "hostname is: `hostname`"
#                    export NODE_ID=${HOSTNAME##*-}
#                    echo "nodeId=$NODE_ID"
          readinessProbe:
            tcpSocket:
              port: 2021
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 2021
            initialDelaySeconds: 15
            periodSeconds: 20
      volumes:
        - name: config
          configMap:
            name: db-config
        - name: storage
          hostPath:
            path: /etc/cassemdb
            type: Directory

# cassemdb service
---
kind: Service
apiVersion: v1
metadata:
  name: cassemdb
  labels:
    app: cassemdb
spec:
  ports:
    - port: 2021
      name: gRPC
      protocol: TCP
    - port: 3021
      name: raft
      protocol: TCP
  clusterIP: None
  selector:
    app: cassemdb
