apiVersion: v1
kind: Deployment
metadata:
  name: casemadm
  namespace: cassem
  labels:
    app: casemadm 
spec:
  selector:
    matchLabels:
      app: cassemdb
  replicas: 1
  template:
    metadata:
      labels:
        app: casemadm
    spec:
      containers:
        - name: casemadm
          image: docker.io/yeqown/casemadm:v0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 20218
              name: http
          volumeMounts:
            - name: casemadm-config
              mountPath: /app/cassemadm
              readOnly: true
      volumes:
        - name: casemadm-config
          configMap:
            name: casemadm-config
      livenessProbe:
        tcpSocket:
          port: 20218
          initialDelaySeconds: 10
          timeoutSeconds: 5
      readinessProbe:
        tcpSocket:
          port: 20218
          initialDelaySeconds: 30
          timeoutSeconds: 15

# cassemadm service
---
apiVersion: v1
kind: Service
metadata:
  name: casemadm
  namespace: cassem
  labels:
    app: casemadm
spec:
  selector:
    matchLabels:
      app: casemadm
  ports:
    - port: 20218
      protocol: TCP
      targetPort: 20218
