# db config
kind: ConfigMap
apiVersion: v1
metadata:
  name: db-config
  namespace: cassem
  labels:
    app: cassemkv
data:
  cassemkv.toml: |
    debug = true
    listenAddr = "0.0.0.0:2021"
    advertiseAddr = "cassemkv.cassem.svc.cluster.local:2021"
    [bolt]
        dir       = "./storage"
        db        = "cassemkv.kv"
    [raft]
        snapCount = 300

# adm config
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: cassemadm-config
  namespace: cassem
  labels:
    app: cassemadmin
data:
  cassemadmin.toml: |
    debug = true
    cassemkv = [
        "cassemkv-0.cassemkv.cassem.svc.cluster.local:2021",
        "cassemkv-1.cassemkv.cassem.svc.cluster.local:2021",
        "cassemkv-2.cassemkv.cassem.svc.cluster.local:2021"
    ]
    [http]
        addr = ":20218"
    [auth]
        sessionSecret = "dev-only-change-me-session-secret"
        bootstrapAccount = "superadmin@example.com"
        bootstrapPassword = "cassem"
        bootstrapNickname = "superadmin"

# agent config
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: agent-config
  namespace: cassem
  labels:
    app: cassemagent
data:
  cassemagent.toml: |
    debug = true
    # seconds for agent registration time to live.
    ttl = 30
    # renew agent registration interval (base), this is better less than ttl.
    renewInterval = 20

    cassemkv = [
        "cassemkv-0.cassemkv.cassem.svc.cluster.local:2021",
        "cassemkv-1.cassemkv.cassem.svc.cluster.local:2021",
        "cassemkv-2.cassemkv.cassem.svc.cluster.local:2021"
    ]
    [server]
        addr = "127.0.0.1:20219"