// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: cassemdb.raft.proto

package kv

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on LogEntry with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *LogEntry) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on LogEntry with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in LogEntryMultiError, or nil
// if none found.
func (m *LogEntry) ValidateAll() error {
	return m.validate(true)
}

func (m *LogEntry) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Action

	// no validation rules for Command

	// no validation rules for CreatedAt

	if len(errors) > 0 {
		return LogEntryMultiError(errors)
	}

	return nil
}

// LogEntryMultiError is an error wrapping multiple validation errors returned
// by LogEntry.ValidateAll() if the designated constraints aren't met.
type LogEntryMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m LogEntryMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m LogEntryMultiError) AllErrors() []error { return m }

// LogEntryValidationError is the validation error returned by
// LogEntry.Validate if the designated constraints aren't met.
type LogEntryValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e LogEntryValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e LogEntryValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e LogEntryValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e LogEntryValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e LogEntryValidationError) ErrorName() string { return "LogEntryValidationError" }

// Error satisfies the builtin error interface
func (e LogEntryValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sLogEntry.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = LogEntryValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = LogEntryValidationError{}

// Validate checks the field values on SetCommand with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *SetCommand) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SetCommand with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in SetCommandMultiError, or
// nil if none found.
func (m *SetCommand) ValidateAll() error {
	return m.validate(true)
}

func (m *SetCommand) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for DeleteKey

	// no validation rules for IsDir

	// no validation rules for SetKey

	if all {
		switch v := interface{}(m.GetValue()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SetCommandValidationError{
					field:  "Value",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SetCommandValidationError{
					field:  "Value",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetValue()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SetCommandValidationError{
				field:  "Value",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return SetCommandMultiError(errors)
	}

	return nil
}

// SetCommandMultiError is an error wrapping multiple validation errors
// returned by SetCommand.ValidateAll() if the designated constraints aren't met.
type SetCommandMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SetCommandMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SetCommandMultiError) AllErrors() []error { return m }

// SetCommandValidationError is the validation error returned by
// SetCommand.Validate if the designated constraints aren't met.
type SetCommandValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SetCommandValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SetCommandValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SetCommandValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SetCommandValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SetCommandValidationError) ErrorName() string { return "SetCommandValidationError" }

// Error satisfies the builtin error interface
func (e SetCommandValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSetCommand.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SetCommandValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SetCommandValidationError{}

// Validate checks the field values on ChangeCommand with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ChangeCommand) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ChangeCommand with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ChangeCommandMultiError, or
// nil if none found.
func (m *ChangeCommand) ValidateAll() error {
	return m.validate(true)
}

func (m *ChangeCommand) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetChange()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ChangeCommandValidationError{
					field:  "Change",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ChangeCommandValidationError{
					field:  "Change",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetChange()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ChangeCommandValidationError{
				field:  "Change",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ChangeCommandMultiError(errors)
	}

	return nil
}

// ChangeCommandMultiError is an error wrapping multiple validation errors
// returned by ChangeCommand.ValidateAll() if the designated constraints
// aren't met.
type ChangeCommandMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ChangeCommandMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ChangeCommandMultiError) AllErrors() []error { return m }

// ChangeCommandValidationError is the validation error returned by
// ChangeCommand.Validate if the designated constraints aren't met.
type ChangeCommandValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ChangeCommandValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ChangeCommandValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ChangeCommandValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ChangeCommandValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ChangeCommandValidationError) ErrorName() string { return "ChangeCommandValidationError" }

// Error satisfies the builtin error interface
func (e ChangeCommandValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sChangeCommand.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ChangeCommandValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ChangeCommandValidationError{}

// Validate checks the field values on AddNodeRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *AddNodeRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AddNodeRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in AddNodeRequestMultiError,
// or nil if none found.
func (m *AddNodeRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *AddNodeRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if !strings.HasPrefix(m.GetRaftAddr(), "http") {
		err := AddNodeRequestValidationError{
			field:  "RaftAddr",
			reason: "value does not have prefix \"http\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetGrpcEndpoint()) < 1 {
		err := AddNodeRequestValidationError{
			field:  "GrpcEndpoint",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return AddNodeRequestMultiError(errors)
	}

	return nil
}

// AddNodeRequestMultiError is an error wrapping multiple validation errors
// returned by AddNodeRequest.ValidateAll() if the designated constraints
// aren't met.
type AddNodeRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AddNodeRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AddNodeRequestMultiError) AllErrors() []error { return m }

// AddNodeRequestValidationError is the validation error returned by
// AddNodeRequest.Validate if the designated constraints aren't met.
type AddNodeRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AddNodeRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AddNodeRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AddNodeRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AddNodeRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AddNodeRequestValidationError) ErrorName() string { return "AddNodeRequestValidationError" }

// Error satisfies the builtin error interface
func (e AddNodeRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAddNodeRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AddNodeRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AddNodeRequestValidationError{}

// Validate checks the field values on AddNodeResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *AddNodeResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AddNodeResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AddNodeResponseMultiError, or nil if none found.
func (m *AddNodeResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *AddNodeResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for NodeId

	if len(errors) > 0 {
		return AddNodeResponseMultiError(errors)
	}

	return nil
}

// AddNodeResponseMultiError is an error wrapping multiple validation errors
// returned by AddNodeResponse.ValidateAll() if the designated constraints
// aren't met.
type AddNodeResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AddNodeResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AddNodeResponseMultiError) AllErrors() []error { return m }

// AddNodeResponseValidationError is the validation error returned by
// AddNodeResponse.Validate if the designated constraints aren't met.
type AddNodeResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AddNodeResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AddNodeResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AddNodeResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AddNodeResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AddNodeResponseValidationError) ErrorName() string { return "AddNodeResponseValidationError" }

// Error satisfies the builtin error interface
func (e AddNodeResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAddNodeResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AddNodeResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AddNodeResponseValidationError{}

// Validate checks the field values on RemoveNodeRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *RemoveNodeRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RemoveNodeRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RemoveNodeRequestMultiError, or nil if none found.
func (m *RemoveNodeRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *RemoveNodeRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetNodeId() <= 0 {
		err := RemoveNodeRequestValidationError{
			field:  "NodeId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return RemoveNodeRequestMultiError(errors)
	}

	return nil
}

// RemoveNodeRequestMultiError is an error wrapping multiple validation errors
// returned by RemoveNodeRequest.ValidateAll() if the designated constraints
// aren't met.
type RemoveNodeRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RemoveNodeRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RemoveNodeRequestMultiError) AllErrors() []error { return m }

// RemoveNodeRequestValidationError is the validation error returned by
// RemoveNodeRequest.Validate if the designated constraints aren't met.
type RemoveNodeRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RemoveNodeRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RemoveNodeRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RemoveNodeRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RemoveNodeRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RemoveNodeRequestValidationError) ErrorName() string {
	return "RemoveNodeRequestValidationError"
}

// Error satisfies the builtin error interface
func (e RemoveNodeRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRemoveNodeRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RemoveNodeRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RemoveNodeRequestValidationError{}

// Validate checks the field values on RemoveNodeResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *RemoveNodeResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RemoveNodeResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RemoveNodeResponseMultiError, or nil if none found.
func (m *RemoveNodeResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *RemoveNodeResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return RemoveNodeResponseMultiError(errors)
	}

	return nil
}

// RemoveNodeResponseMultiError is an error wrapping multiple validation errors
// returned by RemoveNodeResponse.ValidateAll() if the designated constraints
// aren't met.
type RemoveNodeResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RemoveNodeResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RemoveNodeResponseMultiError) AllErrors() []error { return m }

// RemoveNodeResponseValidationError is the validation error returned by
// RemoveNodeResponse.Validate if the designated constraints aren't met.
type RemoveNodeResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RemoveNodeResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RemoveNodeResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RemoveNodeResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RemoveNodeResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RemoveNodeResponseValidationError) ErrorName() string {
	return "RemoveNodeResponseValidationError"
}

// Error satisfies the builtin error interface
func (e RemoveNodeResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRemoveNodeResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RemoveNodeResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RemoveNodeResponseValidationError{}

// Validate checks the field values on ClusterMember with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ClusterMember) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ClusterMember with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ClusterMemberMultiError, or
// nil if none found.
func (m *ClusterMember) ValidateAll() error {
	return m.validate(true)
}

func (m *ClusterMember) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for NodeId

	// no validation rules for RaftAddr

	// no validation rules for GrpcEndpoint

	// no validation rules for Leader

	if len(errors) > 0 {
		return ClusterMemberMultiError(errors)
	}

	return nil
}

// ClusterMemberMultiError is an error wrapping multiple validation errors
// returned by ClusterMember.ValidateAll() if the designated constraints
// aren't met.
type ClusterMemberMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ClusterMemberMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ClusterMemberMultiError) AllErrors() []error { return m }

// ClusterMemberValidationError is the validation error returned by
// ClusterMember.Validate if the designated constraints aren't met.
type ClusterMemberValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ClusterMemberValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ClusterMemberValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ClusterMemberValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ClusterMemberValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ClusterMemberValidationError) ErrorName() string { return "ClusterMemberValidationError" }

// Error satisfies the builtin error interface
func (e ClusterMemberValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sClusterMember.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ClusterMemberValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ClusterMemberValidationError{}

// Validate checks the field values on ListMembersRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListMembersRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListMembersRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListMembersRequestMultiError, or nil if none found.
func (m *ListMembersRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListMembersRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return ListMembersRequestMultiError(errors)
	}

	return nil
}

// ListMembersRequestMultiError is an error wrapping multiple validation errors
// returned by ListMembersRequest.ValidateAll() if the designated constraints
// aren't met.
type ListMembersRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListMembersRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListMembersRequestMultiError) AllErrors() []error { return m }

// ListMembersRequestValidationError is the validation error returned by
// ListMembersRequest.Validate if the designated constraints aren't met.
type ListMembersRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListMembersRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListMembersRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListMembersRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListMembersRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListMembersRequestValidationError) ErrorName() string {
	return "ListMembersRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListMembersRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListMembersRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListMembersRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListMembersRequestValidationError{}

// Validate checks the field values on ListMembersResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListMembersResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListMembersResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListMembersResponseMultiError, or nil if none found.
func (m *ListMembersResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListMembersResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetMembers() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListMembersResponseValidationError{
						field:  fmt.Sprintf("Members[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListMembersResponseValidationError{
						field:  fmt.Sprintf("Members[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListMembersResponseValidationError{
					field:  fmt.Sprintf("Members[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ListMembersResponseMultiError(errors)
	}

	return nil
}

// ListMembersResponseMultiError is an error wrapping multiple validation
// errors returned by ListMembersResponse.ValidateAll() if the designated
// constraints aren't met.
type ListMembersResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListMembersResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListMembersResponseMultiError) AllErrors() []error { return m }

// ListMembersResponseValidationError is the validation error returned by
// ListMembersResponse.Validate if the designated constraints aren't met.
type ListMembersResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListMembersResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListMembersResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListMembersResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListMembersResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListMembersResponseValidationError) ErrorName() string {
	return "ListMembersResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListMembersResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListMembersResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListMembersResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListMembersResponseValidationError{}
